#!/usr/bin/env python3
"""Rewrite commentary for sūtras 4.3.91-105."""

import json


def load_json(path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)

def save_json(path, data):
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

def main():
    commentary_path = 'static/data/layered_commentary.json'
    data = load_json(commentary_path)

    updates = {
        "43091": {
            "en": {
                "simple": "The affix @deva[छ] comes after a word denoting a mountain to mean 'this is his ancestral homeland,' when referring to mercenary soldiers (people who earn their living by arms).\n\n@deva[आयुधजीविन्] means one who lives by weapons—a professional soldier. The phrase @deva[सोऽस्याभिजनः] ('that is his native place') is understood.\n\n**Examples:**\n- @deva[हृद्गोल] (a mountain) + @deva[छ] → @deva[हृद्गोलीयाः] 'mercenary soldiers whose ancestral home is the Hṛdgola mountain'\n- @deva[अन्धकवर्त्तीयाः], @deva[रोहितगिरीयाः]\n\nWhy 'for mercenaries'? For Brāhmaṇas from the Ṛkṣoda mountains, we say @deva[आर्क्षोदाः], not with @deva[छ]. Why 'mountains'? For mercenaries from the town Sāṅkāśya, we say @deva[सांकाश्यकाः], using a different affix.",
                "standard": "The affix @deva[छ] is added after mountain names in the sense of @deva[अभिजन] (ancestral homeland), but only when the referent is @deva[आयुधजीविन्] (one who lives by arms).\n\n**Examples:**\n- @deva[हृद्गोलः पर्वतः अभिजनः एषाम् आयुधजीविनाम्] → @deva[हृद्गोलीयाः] 'mercenaries from Hṛdgola mountain'\n- @deva[अन्धकवर्त्तीयाः], @deva[रोहितगिरीयाः]\n\n**Restrictions:**\n- @deva[आयुधजीविभ्यः] — For non-mercenaries: @deva[आर्क्षोदाः ब्राह्मणाः] (Brāhmaṇas from Ṛkṣoda use @deva[अण्])\n- Mountains only — For mercenaries from a town: @deva[सांकाश्यकाः आयुधजीविनः] (from Sāṅkāśya, not a mountain)",
                "advanced": "This @deva[सूत्र] teaches @deva[छ] after @deva[पर्वत]-denoting words in the @deva[अभिजन] sense, restricted to @deva[आयुधजीविन्] (mercenary soldiers).\n\nThe phrase @deva[सोऽस्याभिजनः] continues from earlier. The @deva[ईय] results from @deva[छ] after the base.\n\n**Examples:** @deva[हृद्गोलीयाः], @deva[अन्धकवर्त्तीयाः], @deva[रोहितगिरीयाः].\n\n**Counter-examples:**\n- Non-@deva[आयुधजीविन्]: @deva[आर्क्षोदाः ब्राह्मणाः] — @deva[अण्] applies by @ref[4.1.83]\n- Non-@deva[पर्वत]: @deva[सांकाश्यकाः आयुधजीविनः] — different affix for town names"
            }
        },
        "43092": {
            "en": {
                "simple": "The affix @deva[ञ्य] comes after words in the @deva[शण्डिकादि] list to mean 'this is his native land.' This overrides the default @deva[अण्].\n\n**Examples:**\n- @deva[शण्डिक] + @deva[ञ्य] → @deva[शाण्डिक्यः]\n- @deva[सर्वसेन] + @deva[ञ्य] → @deva[सार्वसेन्यः]\n\n**The @deva[शण्डिकादि] list:** @deva[शण्डिक], @deva[सर्वसेन], @deva[सर्वकेश], @deva[शक], @deva[शट] (or @deva[सट]), @deva[रक], @deva[शङ्ख], @deva[बोध].",
                "standard": "The affix @deva[ञ्य] comes after words in the @deva[शण्डिकादि] class in the @deva[अभिजन] sense, debarring @deva[अण्] and other affixes.\n\n**Examples:** @deva[शाण्डिक्यः], @deva[सार्वसेन्यः]\n\n**@deva[शण्डिकादि] गण:**\n1. @deva[शण्डिक] 2. @deva[सर्वसेन] 3. @deva[सर्वकेश] 4. @deva[शक] 5. @deva[शट]/​@deva[सट] 6. @deva[रक] 7. @deva[शङ्ख] 8. @deva[बोध]",
                "advanced": "This @deva[सूत्र] prescribes @deva[ञ्य] after @deva[शण्डिकादि] words in the @deva[अभिजन] sense, as an @deva[अपवाद] to the general @deva[अण्] of @ref[4.1.83].\n\n**Examples:** @deva[शाण्डिक्यः], @deva[सार्वसेन्यः]\n\n**@deva[शण्डिकादि] गण:** @deva[शण्डिक], @deva[सर्वसेन], @deva[सर्वकेश], @deva[शक], @deva[शट] (@deva[सट]), @deva[रक], @deva[शङ्ख], @deva[बोध]."
            }
        },
        "43093": {
            "en": {
                "simple": "The affix @deva[अण्] comes after words in the @deva[सिन्ध्वादि] list, and @deva[अञ्] comes after words in the @deva[तक्षशिलादि] list, both meaning 'this is his native land.'\n\n**@deva[सिन्ध्वादि] examples (take @deva[अण्]):**\n- @deva[सिन्धु] → @deva[सैन्धवः]\n- @deva[वर्णु] → @deva[वार्णवः]\n\n**@deva[तक्षशिलादि] examples (take @deva[अञ्]):**\n- @deva[तक्षशिला] → @deva[ताक्षशिलः]\n- @deva[वत्सोद्धरण] → @deva[वात्सोद्धरणः]\n\nMany words in @deva[सिन्ध्वादि] also appear in @deva[कच्छादि] (@ref[4.2.133]). This rule prevents @deva[वुञ्] (@ref[4.2.134]) when the @deva[अभिजन] sense is added.",
                "standard": "The affixes @deva[अण्] and @deva[अञ्] come respectively after @deva[सिन्ध्वादि] and @deva[तक्षशिलादि] words in the @deva[अभिजन] sense.\n\n**@deva[सिन्ध्वादि] (+ @deva[अण्]):** @deva[सैन्धवः], @deva[वार्णवः]\n\n**@deva[तक्षशिलादि] (+ @deva[अञ्]):** @deva[ताक्षशिलः], @deva[वात्सोद्धरणः]\n\nMany @deva[सिन्ध्वादि] words overlap with @deva[कच्छादि] (@ref[4.2.133]), which would otherwise take @deva[वुञ्] by @ref[4.2.134]. This @deva[सूत्र] overrides that when @deva[अभिजन] is meant.\n\n**@deva[सिन्ध्वादि]:** @deva[सिन्धु], @deva[वर्णु], @deva[मधुमत्], @deva[कम्बोज], @deva[साल्व], @deva[कश्मीर], @deva[गन्धार], @deva[किष्किन्धा], @deva[उरसा], @deva[दरद्], @deva[गन्दिका], @deva[कुलून], @deva[दिरसा]\n\n**@deva[तक्षशिलादि]:** @deva[तक्षशिला], @deva[वत्सोद्धरण], @deva[कैर्मेदुर], @deva[ग्रामणी], @deva[छगल], @deva[क्रोष्टुकर्ण], @deva[सिंहकर्ण], @deva[संकुचित], @deva[किंनर], @deva[काण्डधार], @deva[पर्वत], @deva[अवसान], @deva[बर्बर], @deva[कंस], @deva[सरालक]",
                "advanced": "This @deva[सूत्र] teaches @deva[अण्] after @deva[सिन्ध्वादि] and @deva[अञ्] after @deva[तक्षशिलादि] in the @deva[अभिजन] sense.\n\n**Examples:** @deva[सैन्धवः], @deva[वार्णवः]; @deva[ताक्षशिलः], @deva[वात्सोद्धरणः]\n\nMany @deva[सिन्ध्वादि] words also appear in @deva[कच्छादि] (@ref[4.2.133]) and would take @deva[अण्] by that rule. This @deva[सूत्र] prevents @deva[वुञ्] (@ref[4.2.134]) when the additional @deva[अभिजन] sense applies.\n\n**@deva[सिन्ध्वादि] गण:** @deva[सिन्धु], @deva[वर्णु], @deva[मधुमत्], @deva[कम्बोज], @deva[साल्व], @deva[कश्मीर], @deva[गन्धार], @deva[किष्किन्धा], @deva[उरसा]/​@deva[उरस], @deva[दरद्]/​@deva[दरद], @deva[गन्दिका]/​@deva[गब्दिका], @deva[कुलून], @deva[दिरसा]\n\n**@deva[तक्षशिलादि] गण:** @deva[तक्षशिला], @deva[वत्सोद्धरण], @deva[कैर्मेदुर]/​@deva[कौमेदुर], @deva[ग्रामणी], @deva[छगल], @deva[क्रोष्टुकर्ण]/​@deva[कर्णकोष्ठ], @deva[सिंहकर्ण]/​@deva[सिंहकोष्ठ], @deva[संकुचित], @deva[किंनर], @deva[काण्डधार]/​@deva[काण्डवारण], @deva[पर्वत], @deva[अवसान], @deva[बर्बर], @deva[कंस], @deva[सरालक]"
            }
        },
        "43094": {
            "en": {
                "simple": "After specific words, specific affixes are used to mean 'this is his native land':\n\n| Base | Affix | Result |\n|------|-------|--------|\n| @deva[तूदी] | @deva[ढक्] | @deva[तौदेयः] |\n| @deva[शलातुर] | @deva[छण्] | @deva[शालातुरीयः] |\n| @deva[वर्मती] | @deva[ढञ्] | @deva[वार्मतेयः] |\n| @deva[कूचवार] | @deva[यक्] | @deva[कौचवार्यः] |\n\nThese override the default @deva[अण्].",
                "standard": "This @deva[सूत्र] assigns specific affixes to four words in the @deva[अभिजन] sense, debarring @deva[अण्]:\n\n| Base | Affix | Result |\n|------|-------|--------|\n| @deva[तूदी] | @deva[ढक्] | @deva[तौदेयः] |\n| @deva[शलातुर] | @deva[छण्] | @deva[शालातुरीयः] |\n| @deva[वर्मती] | @deva[ढञ्] | @deva[वार्मतेयः] |\n| @deva[कूचवार] | @deva[यक्] | @deva[कौचवार्यः] |",
                "advanced": "This @deva[सूत्र] is a @deva[पृथग्विधान] assigning individual affixes to @deva[तूदी], @deva[शलातुर], @deva[वर्मती], and @deva[कूचवार] in the @deva[अभिजन] sense:\n\n- @deva[तूदी] + @deva[ढक्] → @deva[तौदेयः]\n- @deva[शलातुर] + @deva[छण्] → @deva[शालातुरीयः]\n- @deva[वर्मती] + @deva[ढञ्] → @deva[वार्मतेयः]\n- @deva[कूचवार] + @deva[यक्] → @deva[कौचवार्यः]\n\nThis is an @deva[अपवाद] to @deva[अण्] from @ref[4.1.83]."
            }
        },
        "43095": {
            "en": {
                "simple": "An affix (from the @deva[प्राग्दीव्यतोऽण्] set, @ref[4.1.83]) comes after a word in the first case (nominative) to mean 'this is his object of devotion or love.'\n\nThe word @deva[भक्ति] here means 'worshipping,' 'serving,' or 'loving.'\n\n**Example:** @deva[स्रुघ्नः भक्तिः अस्य] ('Srughna is his object of devotion') → @deva[स्रौघ्नः] 'one devoted to Srughna'\n\nOther examples: @deva[माथुरः] (devoted to Mathurā), @deva[राष्ट्रियः] (devoted to the kingdom)\n\nNote: The @deva[अनुवृत्ति] of @deva[अभिजनः] ceases here. The words @deva[सः] and @deva[अस्य] must be supplied.",
                "standard": "An affix from @deva[प्राग्दीव्यतोऽण्] (@ref[4.1.83]) comes after a word in the @deva[प्रथमा विभक्ति] (nominative) in the sense of @deva[भक्ति] (devotion, worship, or love).\n\n**Example:** @deva[स्रुघ्नः भक्तिः अस्य] → @deva[स्रौघ्नः] 'one devoted to Srughna'\n\nOther examples: @deva[माथुरः], @deva[राष्ट्रियः]\n\nThe @deva[अनुवृत्ति] of @deva[अभिजनः] from earlier @deva[सूत्र]s ceases. The construction requires @deva[सः] and @deva[अस्य] to be read in.",
                "advanced": "This @deva[सूत्र] introduces a new @deva[अर्थ]—@deva[भक्ति] (devotion, worship, love)—for the @deva[प्राग्दीव्यतोऽण्] affixes (@ref[4.1.83]).\n\nThe @deva[प्रातिपदिक] stands in @deva[प्रथमा विभक्ति] in the @deva[योग] (syntactic construction). The @deva[अनुवृत्ति] of @deva[अभिजनः] stops here; instead, @deva[सः भक्तिः अस्य] ('that is his object of devotion') must be supplied.\n\n**Examples:** @deva[स्रुघ्नः भक्तिः अस्य] → @deva[स्रौघ्नः]; @deva[माथुरः], @deva[राष्ट्रियः]"
            }
        },
        "43096": {
            "en": {
                "simple": "After a word denoting something without consciousness (@deva[अचेतन])—but not a country name or a time word—the affix @deva[ठक्] is used to mean 'this is his object of devotion.'\n\nThis overrides @deva[अण्] and @deva[छ].\n\n**Examples:**\n- @deva[अपूपः भक्तिः अस्य] ('cakes are his love') → @deva[आपूपिकः] 'one who loves cakes'\n- @deva[शाष्कुलिकः] 'one who loves śaṣkuli (a type of pastry)'\n- @deva[पायसिकः] 'one who loves pāyasa (rice pudding)'\n\nWhy 'without consciousness'? For a conscious being: @deva[दैवदत्तः] (uses @deva[अण्], not @deva[ठक्])\n\nWhy 'not a country'? For a country: @deva[स्रौघ्नः] (uses @deva[अण्])\n\nWhy 'not time'? For a season: @deva[ग्रैष्मः] 'who loves summer' (uses @deva[अण्])",
                "standard": "The affix @deva[ठक्] comes in the @deva[भक्ति] sense after @deva[अचेतन] (non-conscious) words that are neither @deva[जनपद] (country) names nor @deva[काल] (time) words. This debars @deva[अण्] and @deva[छ].\n\n**Examples:** @deva[आपूपिकः] (loves cakes), @deva[शाष्कुलिकः], @deva[पायसिकः]\n\n**Counter-examples:**\n- @deva[चेतन] (conscious): @deva[दैवदत्तः] (devotee of Devadatta)—@deva[अण्]\n- @deva[जनपद]: @deva[स्रौघ्नः] (devoted to Srughna)—@deva[अण्]\n- @deva[काल]: @deva[ग्रैष्मः] (loves summer)—@deva[अण्]",
                "advanced": "This @deva[सूत्र] teaches @deva[ठक्] after @deva[अचेतन] words in the @deva[भक्ति] sense, excluding @deva[जनपद] and @deva[काल] words. It serves as an @deva[अपवाद] to @deva[अण्] (@ref[4.1.83]) and @deva[छ].\n\n**Examples:** @deva[अपूपभक्तिः अस्य] → @deva[आपूपिकः]; @deva[शाष्कुलिकः], @deva[पायसिकः]\n\n**Counter-examples:**\n- @deva[चेतन]: @deva[दैवदत्तः]—@deva[अण्] by @ref[4.1.83]\n- @deva[जनपद]: @deva[स्रौघ्नः]—@deva[अण्] by @ref[4.3.95]\n- @deva[काल]: @deva[ग्रैष्मः]—@deva[अण्] by @ref[4.1.83]"
            }
        },
        "43097": {
            "en": {
                "simple": "The affix @deva[ठञ्] comes after @deva[महाराज] to mean 'this is his object of devotion.' This overrides @deva[अण्].\n\n**Example:** @deva[महाराजः भक्तिः अस्य] → @deva[माहाराजिकः] 'one who serves or loves the Mahārāja'\n\nThe difference between @deva[ठञ्] (this rule) and @deva[ठक्] (previous rule) is only in accent.",
                "standard": "The affix @deva[ठञ्] comes after @deva[महाराज] in the @deva[भक्ति] sense, debarring @deva[अण्].\n\n**Example:** @deva[माहाराजिकः] 'one devoted to the Mahārāja'\n\nThe distinction between @deva[ठञ्] and @deva[ठक्] (@ref[4.3.96]) lies in accent only.",
                "advanced": "This @deva[सूत्र] prescribes @deva[ठञ्] specifically after @deva[महाराज] in the @deva[भक्ति] sense. It debars @deva[अण्] from @ref[4.1.83].\n\n**Example:** @deva[माहाराजिकः]\n\nThe difference between @deva[ठञ्] and @deva[ठक्] (@ref[4.3.96]) is accentual: @deva[ठञ्] has @deva[ञ्] as @deva[इत्] for accent purposes."
            }
        },
        "43098": {
            "en": {
                "simple": "The affix @deva[वुञ्] comes after @deva[वासुदेव] and @deva[अर्जुन] to mean 'this is his object of devotion.' This overrides @deva[छ] and @deva[अण्].\n\n**Examples:**\n- @deva[वासुदेवः भक्तिः अस्य] → @deva[वासुदेवकः] 'a devotee of Vāsudeva'\n- @deva[अर्जुनः भक्तिः अस्य] → @deva[अर्जुनकः] 'a devotee of Arjuna'\n\nQuestion: @deva[वासुदेव] as a Kṣatriya name would take @deva[वुञ्] by the next rule anyway. Why mention it here?\n\nAnswer: Here @deva[वासुदेव] means God (the one in whom all beings dwell: @deva[वसति अस्मिन्]), not the Kṣatriya designation.\n\nNote: By @ref[2.2.34], a word with fewer vowels should come first in a compound. Placing @deva[वासुदेव] before @deva[अर्जुन] indicates that words denoting objects of reverence are placed first.",
                "standard": "The affix @deva[वुञ्] comes after @deva[वासुदेव] and @deva[अर्जुन] in the @deva[भक्ति] sense, debarring @deva[छ] and @deva[अण्].\n\n**Examples:** @deva[वासुदेवकः], @deva[अर्जुनकः]\n\nWhy include @deva[वासुदेव] when @deva[वुञ्] would apply by @ref[4.3.99] for Kṣatriya names? Here @deva[वासुदेव] denotes God (@deva[वसति अस्मिन्]—'in whom all dwell'), not a Kṣatriya.\n\nThe ordering—@deva[वासुदेव] before @deva[अर्जुन] despite having more vowels—is a @deva[ज्ञापक] that words denoting reverence take precedence over the @deva[अल्पाच्तर] rule (@ref[2.2.34]).",
                "advanced": "This @deva[सूत्र] prescribes @deva[वुञ्] after @deva[वासुदेव] and @deva[अर्जुन] in the @deva[भक्ति] sense, debarring @deva[छ] and @deva[अण्].\n\n**Examples:** @deva[वासुदेवकः], @deva[अर्जुनकः]\n\n**Why @deva[वासुदेव] here?** The next @deva[सूत्र] (@ref[4.3.99]) teaches @deva[वुञ्] after Kṣatriya names. But @deva[वासुदेव] here denotes the deity (@deva[वसति अस्मिन्] 'in whom all dwell'), not the Kṣatriya.\n\n**@deva[ज्ञापक]:** The ordering @deva[वासुदेव]-@deva[अर्जुन] violates @ref[2.2.34] (@deva[अल्पाच्तरम्]). This indicates a meta-rule: words denoting @deva[पूज्य] (objects of reverence) are placed first."
            }
        },
        "43099": {
            "en": {
                "simple": "The affix @deva[वुञ्] optionally comes after a word denoting a @deva[गोत्र] (patronymic lineage) or a Kṣatriya to mean 'this is his object of devotion.' This overrides @deva[अण्] and @deva[छ].\n\n**@deva[गोत्र] examples:**\n- @deva[ग्लौचुकायनी भक्तिः अस्य] → @deva[ग्लौचुकायनकः] 'devotee of Glaucukāyanī'\n- @deva[औपगवकः], @deva[कापटवकः]\n\n**Kṣatriya examples:**\n- @deva[नाकुलकः] 'devotee of Nakula'\n- @deva[साहदेवकः] 'devotee of Sahadeva'\n- @deva[साम्बकः] 'devotee of Sāmba'\n\nThe word @deva[आख्या] in the rule indicates these must be names of famous, well-known Kṣatriyas, not just anyone of that profession.\n\nThe word @deva[बहुलम्] ('variously') shows this rule is not universal. Counter-example: @deva[पाणिनोः भक्तिः अस्य] → @deva[पाणिनीयः] (using @deva[छ], not @deva[वुञ्]).\n\nNote: @deva[गोत्र] here means any word formed with a patronymic affix, not just grammatical @deva[गोत्र] in the technical sense.",
                "standard": "The affix @deva[वुञ्] comes optionally (@deva[बहुलम्]) after @deva[गोत्र] or @deva[क्षत्रियाख्या] words in the @deva[भक्ति] sense, debarring @deva[अण्] and @deva[छ].\n\n**@deva[गोत्र] examples:** @deva[ग्लौचुकायनकः], @deva[औपगवकः], @deva[कापटवकः]\n\n**@deva[क्षत्रिय] examples:** @deva[नाकुलकः], @deva[साहदेवकः], @deva[साम्बकः]\n\n@deva[आख्या] indicates these must be famous Kṣatriya names, not ordinary warriors.\n\n@deva[बहुलम्] shows optionality. Counter-examples using @deva[छ]: @deva[पाणिनीयः], @deva[पौरवीयः]\n\nThe term @deva[गोत्र] here means any patronymically-derived word, not the technical grammatical @deva[गोत्र].",
                "advanced": "This @deva[सूत्र] teaches @deva[वुञ्] after @deva[गोत्र] and @deva[क्षत्रियाख्या] words in the @deva[भक्ति] sense, debarring @deva[अण्] and @deva[छ].\n\n**Examples:** @deva[ग्लौचुकायनकः], @deva[औपगवकः], @deva[कापटवकः]; @deva[नाकुलकः], @deva[साहदेवकः], @deva[साम्बकः]\n\n**@deva[आख्या]:** The term restricts application to well-known Kṣatriya names, not ordinary professionals.\n\n**@deva[बहुलम्]:** The rule is optional. Alternatives: @deva[पाणिनीयः], @deva[पौरवीयः] (with @deva[छ]).\n\n**Technical note:** @deva[गोत्र] here encompasses any @deva[युवापत्यप्रत्ययान्त] (word with a patronymic affix), not just @deva[गोत्र] in the strict grammatical sense of @ref[4.1.162]."
            }
        },
        "43100": {
            "en": {
                "simple": "For words denoting Kṣatriya princes (lords of territories) that have the same form in the plural as the territory name, the base and affix for the @deva[भक्ति] (devotion) sense are the same as those for the territory word.\n\n**Example:** The word @deva[अङ्गाः] means both 'the Aṅga country' and 'the Kṣatriya princes of Aṅga.'\n- @deva[अङ्गाः जनपदः भक्तिः अस्य] → @deva[आङ्गकः] (by @deva[वुञ्] from @ref[4.2.125]) 'one who loves the Aṅga country'\n- @deva[अङ्गाः क्षत्रियाः भक्तिः अस्य] → @deva[आङ्गकः] 'one who loves the Aṅga princes'\n\nThe word @deva[सर्वम्] ('everything') in the rule means not just the affixes but also the bases are treated alike.\n\nFor singular/dual forms of prince-denoting words (which differ from territory words), the plural base @deva[मद्राः] is still used: @deva[मद्रः भक्तिः अस्य] or @deva[माद्रौ भक्तिः अस्य] → @deva[मद्रकः].\n\nWhy 'princes' (@deva[जनपदिनाम्])? For Brāhmaṇas: @deva[पंचालाः ब्राह्मणाः भक्तिः अस्य] → @deva[पांचालः] (with general @deva[अण्]).",
                "standard": "For @deva[जनपदिन्] (territorial lords/princes) whose plural form matches the @deva[जनपद] (territory) name, the @deva[भक्ति]-sense derivative follows the same pattern as the @deva[जनपद] derivative.\n\n**Principle:** @deva[जनपदवत् सर्वम्]—'everything is like the @deva[जनपद] word.'\n\n**Example:** @deva[अङ्गाः] = both 'Aṅga country' and 'Aṅga princes'\n- From territory: @deva[आङ्गकः] (by @deva[वुञ्], @ref[4.2.125])\n- From princes: @deva[आङ्गकः] (same)\n\nSimilarly: @deva[वाङ्गकः], @deva[सौह्मकः], @deva[पौन्द्रकः]\n\n**Singular/dual:** The @deva[ताद्राज] affix is elided only in plural. Yet this rule extends to singular/dual—the @deva[जनपद] base is used: @deva[माद्रः] or @deva[माद्रौ भक्तिः अस्य] → @deva[मद्रकः] (not @deva[माद्रकः]).\n\n**Restriction:** @deva[जनपदिनाम्] limits this to princes. @deva[पंचालाः ब्राह्मणाः भक्तिः अस्य] → @deva[पांचालः] (general @deva[अण्]).\n\n**@deva[समानशब्द]:** The prince and territory words must have identical plural forms. Counter-example: @deva[अनुषण्डः जनपदः], @deva[पौरवः राजा] → @deva[पौरवीयः] (different words).",
                "advanced": "This @deva[सूत्र] establishes an @deva[अतिदेश] (analogical extension): @deva[जनपदिन्] (territorial princes) whose @deva[बहुवचन] form matches the @deva[जनपद] name take @deva[भक्ति]-affixes exactly as @deva[जनपद] words do.\n\n**Analysis:** @deva[जनपदिनां बहुवचने जनपदेन समानशब्दानां जनपदवत् सर्वम्]\n\n- @deva[जनपदिनाम्]: gen. pl. of @deva[जनपदिन्] (lords of territories)\n- @deva[बहुवचने]: in the plural\n- @deva[जनपदेन समानशब्दानाम्]: having the same form as the @deva[जनपद] word\n- @deva[जनपदवत् सर्वम्]: everything follows @deva[जनपद] pattern\n\n**Application:** The @deva[भक्ति] affixes from @ref[4.2.124] ff. apply. Thus @deva[अङ्गाः क्षत्रियाः भक्तिः अस्य] → @deva[आङ्गकः] (by @deva[वुञ्], @ref[4.2.125]).\n\n**@deva[सर्वम्]:** Both affix and base follow @deva[जनपद]. In singular/dual, @deva[ताद्राज] is not elided for princes (@deva[माद्रः], @deva[माद्रौ]), yet the @deva[जनपद]-base @deva[मद्र] is used: @deva[मद्रकः].\n\n**@deva[बहुवचने]:** Though @deva[समानशब्दता] occurs only in plural, the @deva[अतिदेश] extends to singular/dual.\n\n**Counter-examples:**\n- Non-princes: @deva[पंचालाः ब्राह्मणाः भक्तिः अस्य] → @deva[पांचालः] (@deva[अण्])\n- Non-@deva[समानशब्द]: @deva[अनुषण्डः जनपदः], @deva[पौरवः राजा] → @deva[पौरवीयः]"
            }
        },
        "43101": {
            "en": {
                "simple": "An affix (from the @deva[प्राग्दीव्यतोऽण्] set, @ref[4.1.83]) comes after a word in the instrumental case (third case) to mean 'enounced or taught by him.'\n\nThe word @deva[प्रोक्त] means 'preeminently spoken'—teaching or promulgating, as distinct from @deva[कृत] ('composed'). The sense of @deva[कृत] was already taught at @ref[4.3.16].\n\n**Examples:**\n- @deva[पाणिनिना प्रोक्तम्] → @deva[पाणिनीयम्] 'the grammar taught by Pāṇini'\n- @deva[आपिशलम्], @deva[काशकृत्स्नम्]\n- @deva[अन्येन कृता माथुरेण प्रोक्ता] = @deva[माथुरी वृत्तिः] 'a commentary composed by one person but taught by a Mathura scholar'\n\nThis rule applies to the Vedas (which are eternal, not 'composed') and to works where the author and the promulgator are different people.",
                "standard": "An affix from @deva[प्राग्दीव्यतोऽण्] (@ref[4.1.83]) comes after a word in @deva[तृतीया विभक्ति] (instrumental) in the @deva[प्रोक्त] (enounced/taught) sense.\n\n@deva[प्रोक्त] (@deva[प्रकर्षेण उक्तम्]) means 'promulgated' or 'taught,' distinct from @deva[कृत] ('composed'), which was treated at @ref[4.3.16].\n\n**Examples:** @deva[पाणिनीयम्] (taught by Pāṇini), @deva[आपिशलम्], @deva[काशकृत्स्नम्]\n\n**Application:** Works like @deva[छन्दस्] (Vedas), which are eternal and hence not 'composed' but only 'revealed' by seers, or works where the author and teacher differ: @deva[माथुरी वृत्तिः] (composed by one, promulgated by a Mathura scholar).\n\nSome argue this @deva[सूत्र] overlaps with @ref[4.3.16]. The distinction: @deva[प्रोक्त] = revelation/teaching; @deva[कृत] = authorship.",
                "standard": "An affix from @deva[प्राग्दीव्यतोऽण्] (@ref[4.1.83]) comes after a word in @deva[तृतीया विभक्ति] (instrumental) in the @deva[प्रोक्त] (enounced/taught) sense.\n\n@deva[प्रोक्त] (@deva[प्रकर्षेण उक्तम्]) means 'promulgated' or 'taught,' distinct from @deva[कृत] ('composed'), which was treated at @ref[4.3.16].\n\n**Examples:** @deva[पाणिनीयम्] (taught by Pāṇini), @deva[आपिशलम्], @deva[काशकृत्स्नम्]\n\n**Application:** Works like @deva[छन्दस्] (Vedas), which are eternal and hence not 'composed' but only 'revealed' by seers, or works where the author and teacher differ: @deva[माथुरी वृत्तिः] (composed by one, promulgated by a Mathura scholar).",
                "advanced": "This @deva[सूत्र] introduces the @deva[प्रोक्त] sense for @deva[प्राग्दीव्यतोऽण्] affixes (@ref[4.1.83]), with the base in @deva[तृतीया विभक्ति].\n\n@deva[प्रोक्त] = @deva[प्रकर्षेण उक्तम्]—teaching, promulgating—as opposed to @deva[कृत] (composing), which is covered by @ref[4.3.16] (@deva[कृते ग्रन्थे]).\n\n**Examples:** @deva[पाणिनीयम्], @deva[आपिशलम्], @deva[काशकृत्स्नम्]\n\n**Scope:** This applies when:\n1. The work is @deva[अपौरुषेय] (like @deva[छन्दस्])—not composed but revealed. The @deva[ऋषि]s 'remember' the eternal @deva[वेद] and promulgate it anew each @deva[कल्प]: @deva[काठकम्], @deva[कालापकम्], @deva[मौदकम्].\n2. The author and teacher differ: @deva[माथुरी वृत्तिः] (composed by another, taught by a Mathura scholar).\n\nSome consider this @deva[सूत्र] nearly redundant with @ref[4.3.16], but the distinction between @deva[प्रोक्त] (revelation/teaching) and @deva[कृत] (composition) is significant."
            }
        },
        "43102": {
            "en": {
                "simple": "The affix @deva[छण्] comes in the @deva[प्रोक्त] (enounced) sense after the words @deva[तित्तिरि], @deva[वरतन्तु], @deva[खण्डिक], and @deva[उख].\n\n**Examples:**\n- @deva[तित्तिरिणा प्रोक्तम्] → @deva[तैत्तिरीयाः] 'those who study the Veda taught by Tittiri'\n- @deva[वारतन्तवीयाः], @deva[खाण्डिकीयाः], @deva[औखीयाः]\n\nAccording to the Kāśikā, this rule applies only to Vedic works (@deva[छन्दस्]), not to secular verses. So @deva[तित्तिरिणा प्रोक्तः श्लोकः] would not take this affix.",
                "standard": "The affix @deva[छण्] comes after @deva[तित्तिरि], @deva[वरतन्तु], @deva[खण्डिक], and @deva[उख] in the @deva[प्रोक्त] sense.\n\n**Examples:** @deva[तैत्तिरीयाः], @deva[वारतन्तवीयाः], @deva[खाण्डिकीयाः], @deva[औखीयाः]\n\nPer the Kāśikā, this is restricted to @deva[छन्दस्] (Vedic literature); the sense @deva[तद्विषयता] (@ref[4.2.66]) continues. Secular compositions (@deva[श्लोक]) by @deva[तित्तिरि] would not take this affix.",
                "advanced": "This @deva[सूत्र] teaches @deva[छण्] after @deva[तित्तिरि], @deva[वरतन्तु], @deva[खण्डिक], and @deva[उख] in the @deva[प्रोक्त] sense.\n\n**Examples:** @deva[तैत्तिरीयाः], @deva[वारतन्तवीयाः], @deva[खाण्डिकीयाः], @deva[औखीयाः]\n\n**Restriction:** Per the Kāśikā, @deva[छन्दस्] continues from @ref[4.3.106], and @deva[तद्विषयता] from @ref[4.2.66]. Thus this applies only to Vedic works, not to secular @deva[श्लोक]s: @deva[तित्तिरिणा प्रोक्तः श्लोकः] would not take @deva[छण्]."
            }
        },
        "43103": {
            "en": {
                "simple": "The affix @deva[णिनि] comes in the @deva[प्रोक्त] (enounced) sense after the words @deva[काश्यप] and @deva[कौशिक], when they denote Vedic seers (@deva[ऋषि]s). This overrides @deva[छ].\n\nThe @deva[ण्] in @deva[णिनि] causes @deva[वृद्धि] of the first vowel.\n\n**Examples:**\n- @deva[काश्यपेन प्रोक्तम्] → @deva[काश्यपिनः] 'those who study the Kalpa taught by the seer Kāśyapa'\n- @deva[कौशिकिनः] 'those who study the work taught by Kauśika'\n\nLike the previous rule, this applies only to Vedic works.\n\nWhy 'Vedic seers'? For a modern person of the Kāśyapa gotra: @deva[इदानीन्तनेन गोत्रकाश्यपेन प्रोक्तम्] → @deva[काश्यपीयम्] (with @deva[छ], not @deva[णिनि]).",
                "standard": "The affix @deva[णिनि] comes after @deva[काश्यप] and @deva[कौशिक] in the @deva[प्रोक्त] sense when they denote @deva[ऋषि]s (Vedic seers). This debars @deva[छ].\n\nThe @deva[ण्] causes @deva[वृद्धि].\n\n**Examples:** @deva[काश्यपिनः], @deva[कौशिकिनः]\n\nRestricted to Vedic works, as with @ref[4.3.102].\n\n**Counter-example:** A modern @deva[गोत्र]-Kāśyapa: @deva[इदानीन्तनेन गोत्रकाश्यपेन प्रोक्तम्] → @deva[काश्यपीयम्] (with @deva[छ]).",
                "advanced": "This @deva[सूत्र] teaches @deva[णिनि] after @deva[काश्यप] and @deva[कौशिक] in the @deva[प्रोक्त] sense, restricted to @deva[ऋषि]s (Vedic seers). It debars @deva[छ].\n\nThe @deva[ण्] in @deva[णिनि] triggers @deva[वृद्धि] (relevant for the subsequent @deva[सूत्र]).\n\n**Examples:** @deva[काश्यपिनः], @deva[कौशिकिनः]\n\n**Restriction:** @deva[ऋषिभ्यः]—only ancient seers, not modern @deva[गोत्र] members. Counter-example: @deva[इदानीन्तनेन गोत्रकाश्यपेन प्रोक्तम्] → @deva[काश्यपीयम्] (with @deva[छ])."
            }
        },
        "43104": {
            "en": {
                "simple": "The affix @deva[णिनि] comes in the @deva[प्रोक्त] (enounced) sense after words denoting the direct pupils of @deva[कलापि] and @deva[वैशम्पायन]. This overrides @deva[अण्] and @deva[छ].\n\n**Pupils of @deva[कलापि]:** @deva[हरिद्रु], @deva[छगली], @deva[तुम्बुरु], @deva[उलप]\n\n**Pupils of @deva[वैशम्पायन]:** @deva[आलम्बि], @deva[चरक], @deva[पलङ्ग], @deva[कमल], @deva[ॠचाभ], @deva[आरुणि], @deva[ताण्ड्य], @deva[श्यामायन], @deva[कठ], @deva[कलापि]\n\n**Examples:**\n- @deva[हारिद्रविणः] 'those who study works taught by Haridru'\n- @deva[तुम्बुरविणः], @deva[औलपिनः]\n- @deva[आलम्बिनः], @deva[पालङ्गिनः], @deva[आरुणिनः], @deva[कामलिनः], @deva[ताण्डिनः], @deva[श्यामायनिनः]\n\nSpecial cases: @deva[छगली] takes @deva[धिनुक्] (@ref[4.3.109]); @deva[कठ] has the affix elided (@ref[4.3.107]); @deva[कलापी] takes @deva[अण्] (@ref[4.3.108]).\n\n'Direct pupils' means immediate disciples, not pupils of pupils. Otherwise @deva[कलापि], being a pupil of @deva[वैशम्पायन], would be redundant.",
                "standard": "The affix @deva[णिनि] comes after words denoting direct pupils of @deva[कलापि] and @deva[वैशम्पायन] in the @deva[प्रोक्त] sense, debarring @deva[अण्] and @deva[छ].\n\n**@deva[कलापि]-शिष्याः:** @deva[हरिद्रु], @deva[छगली], @deva[तुम्बुरु], @deva[उलप]\n\n**@deva[वैशम्पायन]-शिष्याः:** @deva[आलम्बि], @deva[पलङ्ग], @deva[कमल], @deva[ॠचाभ], @deva[आरुणि], @deva[ताण्ड्य], @deva[श्यामायन], @deva[कठ], @deva[कलापि]\n\n@deva[चरक] = @deva[वैशम्पायन], hence @deva[चरकाः] = pupils of @deva[वैशम्पायन].\n\n**Examples:** @deva[हारिद्रविणः], @deva[तुम्बुरविणः], @deva[औलपिनः]; @deva[आलम्बिनः], @deva[पालङ्गिनः], @deva[आर्चाभिनः], @deva[आरुणिनः], @deva[कामलिनः], @deva[ताण्डिनः], @deva[श्यामायनिनः]\n\n**Special cases:**\n- @deva[छगली] → @deva[धिनुक्] (@ref[4.3.109])\n- @deva[कठ] → affix @deva[लुक्] (@ref[4.3.107])\n- @deva[कलापी] → @deva[अण्] (@ref[4.3.108])\n\n'Pupils' means direct disciples only. @deva[खाण्डायन] (pupil of @deva[कठ], who is pupil of @deva[वैशम्पायन]) appears in @deva[शौनकादि] (@ref[4.3.106]), not here.",
                "advanced": "This @deva[सूत्र] teaches @deva[णिनि] after words denoting direct pupils of @deva[कलापि] and @deva[वैशम्पायन] in the @deva[प्रोक्त] sense, debarring @deva[अण्] and @deva[छ].\n\n**Kārikā:**\n@deva[हरिद्रुरेषां प्रथमस्ततश्छगलितुम्बुरू] ।\n@deva[उलपेन चतुर्थेन कालापकमिहोच्यते] ॥\n@deva[आलम्बिश्चरकः प्राचां पलङ्गकमलावुभौ] ।\n@deva[ऋचाभारुणिताण्ड्याश्च मद्ध्यमीयास्त्रयोऽपरे] ॥\n@deva[श्यामायन उदीच्येषु उक्तः कठकलापिनोः] ।\n\n**@deva[कलापि]-शिष्याः (4):** @deva[हरिद्रु], @deva[छगली], @deva[तुम्बुरु], @deva[उलप]\n\n**@deva[वैशम्पायन]-शिष्याः (9):** @deva[आलम्बि], @deva[पलङ्ग], @deva[कमल], @deva[ॠचाभ], @deva[आरुणि], @deva[ताण्ड्य], @deva[श्यामायन], @deva[कठ], @deva[कलापि]\n\n@deva[चरक] = @deva[वैशम्पायन], hence @deva[चरकाः] = his pupils.\n\n**Examples:** @deva[हारिद्रविणः], @deva[तुम्बुरविणः], @deva[औलपिनः]; @deva[आलम्बिनः], @deva[पालङ्गिनः], @deva[आर्चाभिनः], @deva[आरुणिनः], @deva[कामलिनः], @deva[ताण्डिनः], @deva[श्यामायनिनः]\n\n**Special rules:**\n- @deva[छगली] → @deva[धिनुक्] by @ref[4.3.109]\n- @deva[कठ] → @deva[लुक्] by @ref[4.3.107]\n- @deva[कलापी] → @deva[अण्] by @ref[4.3.108]\n\n**Direct pupils only:** Had 'pupil of pupil' been meant, @deva[कलापि] (pupil of @deva[वैशम्पायन]) would include @deva[कलापि]'s own pupils, making separate mention redundant. Similarly, @deva[खाण्डायन] (pupil of @deva[कठ]) appears in @deva[शौनकादि] (@ref[4.3.106]), confirming direct-pupil restriction."
            }
        },
        "43105": {
            "en": {
                "simple": "The affix @deva[णिनि] comes in the @deva[प्रोक्त] (enounced) sense after a word in the instrumental case when it refers to a @deva[ब्राह्मण] (a class of Vedic prose text) or a @deva[कल्प] (ritual manual) that was taught by ancient sages.\n\n**@deva[ब्राह्मण] examples:**\n- @deva[शाट्यायनिनः] 'those who study the Brāhmaṇa taught by Śāṭyāyana'\n- @deva[ऐतरेयिणः]\n\n**@deva[कल्प] examples:**\n- @deva[पैङ्गीकल्पः] 'the Kalpa of Paiṅgi'\n- @deva[आरुणपराजी]\n\nWhy 'ancient sages' (@deva[पुराणप्रोक्त])? For modern teachers: @deva[याज्ञवल्कानि ब्राह्मणानि] 'the Brāhmaṇas of Yājñavalkya' (takes @deva[अण्], not @deva[णिनि]), @deva[आश्मरथः कल्पः] 'the Kalpa of Āśmaratha' — these are modern sages, so @deva[णिनि] doesn't apply.",
                "standard": "The affix @deva[णिनि] comes in the @deva[प्रोक्त] sense after a word in @deva[तृतीया] when it denotes @deva[ब्राह्मण] or @deva[कल्प] literature taught by @deva[पुराण] (ancient sages).\n\n**@deva[ब्राह्मण] examples:** @deva[शाट्यायनिनः], @deva[ऐतरेयिणः]\n\n**@deva[कल्प] examples:** @deva[पैङ्गीकल्पः], @deva[आरुणपराजी]\n\n**@deva[पुराणप्रोक्त] restriction:** Works of modern sages use other affixes: @deva[याज्ञवल्कानि ब्राह्मणानि], @deva[आश्मरथः कल्पः] — @deva[यज्ञवल्क्य] and @deva[अश्मरथ] being relatively recent.\n\nThis sense restriction also affects the @deva[तद्विषय] affix (@ref[4.2.66]): the word @deva[ब्राह्मण] in @ref[4.2.66] is implicitly limited to @deva[पुराणप्रोक्त].",
                "advanced": "This @deva[सूत्र] specifies that @deva[णिनि] applies in the @deva[प्रोक्त] sense for @deva[ब्राह्मण] and @deva[कल्प] literature, with the additional condition @deva[पुराणप्रोक्तेषु] (taught by ancient sages).\n\n@deva[पुराण] = @deva[पुरातन] (ancient).\n\n**@deva[ब्राह्मण]:** @deva[शाट्यायनिनः], @deva[ऐतरेयिणः]\n\n**@deva[कल्प]:** @deva[पैङ्गीकल्पः], @deva[आरुणपराजी]\n\n**Counter-examples (non-@deva[पुराण]):** @deva[याज्ञवल्कानि ब्राह्मणानि], @deva[आश्मरथः कल्पः] — @deva[यज्ञवल्क्य] and @deva[अश्मरथ] are modern sages, so @deva[णिनि] is blocked; @deva[अण्] applies instead (@ref[6.4.151]).\n\n**Technical note:** The @deva[पुराणप्रोक्त] restriction also bounds the @deva[तद्विषय] affix: @deva[ब्राह्मण] in @ref[4.2.66] is implicitly restricted to ancient @deva[ब्राह्मण]s."
            }
        }
    }

    # Fix 43101 which had duplicate 'standard' key
    updates["43101"]["en"]["standard"] = "An affix from @deva[प्राग्दीव्यतोऽण्] (@ref[4.1.83]) comes after a word in @deva[तृतीया विभक्ति] (instrumental) in the @deva[प्रोक्त] (enounced/taught) sense.\n\n@deva[प्रोक्त] (@deva[प्रकर्षेण उक्तम्]) means 'promulgated' or 'taught,' distinct from @deva[कृत] ('composed'), which was treated at @ref[4.3.16].\n\n**Examples:** @deva[पाणिनीयम्] (taught by Pāṇini), @deva[आपिशलम्], @deva[काशकृत्स्नम्]\n\n**Application:** Works like @deva[छन्दस्] (Vedas), which are eternal and hence not 'composed' but only 'revealed' by seers, or works where the author and teacher differ: @deva[माथुरी वृत्तिः] (composed by one, promulgated by a Mathura scholar).\n\nSome argue this @deva[सूत्र] overlaps with @ref[4.3.16]. The distinction: @deva[प्रोक्त] = revelation/teaching; @deva[कृत] = authorship."

    # Update the data
    for key, value in updates.items():
        data[key] = value

    save_json(commentary_path, data)
    print(f"Updated {len(updates)} sūtras (4.3.91-105)")

if __name__ == "__main__":
    main()
