#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Rewrite commentary for sutras 3.4.61-3.4.75 (Batch 5 of 3.4)."""

import json

with open('static/data/layered_commentary.json', 'r', encoding='utf-8') as f:
    commentary = json.load(f)

updates = {
    "34061": {
        "en": {
            "simple": "Both @deva[क्त्वा] and @deva[णमुल्] come after @deva[कृ] 'to make' and @deva[भू] 'to be' when a @deva[स्वाङ्ग] word (denoting one's own body part) ending in the @deva[तस्] affix (@ref[5.3.78]) is compounded. Both affixes apply to both roots—no 'respective allocation' (@ref[1.3.10]). Examples with @deva[कृ]: @deva[मुखतः] @deva[कृत्य] @deva[गतः], @deva[मुखतः] @deva[कृत्वा] @deva[गतः], @deva[मुखतः] @deva[कारं] @deva[गतः] 'having turned face-forward, he went'. With @deva[भू]: @deva[पृष्ठतःभूय] @deva[तिष्ठति], @deva[पृष्ठतः] @deva[भूत्वा] @deva[तिष्ठति], @deva[पृष्ठतः] @deva[भावं] @deva[तिष्ठति] 'having turned back, he stands'. The rule requires @deva[तस्] as an affix—not when @deva[तस्] is a verb root: @deva[मुखतः] @deva[कृत्वा] @deva[गतः] (where @deva[मुखतः] = @deva[मुखे] @deva[तस्यति] 'throws in the mouth').",
            "standard": "@deva[क्त्वा]/@deva[णमुल्] apply to @deva[कृ]/@deva[भू] when a @deva[स्वाङ्ग] word (body part, defined @ref[3.4.54]) ends in the @deva[तसिल्]/@deva[तसि] affix (@ref[5.3.78]ff.). No @deva[यथासंख्य] (@ref[1.3.10])—both affixes apply to both roots. @deva[मुखतः] @deva[कृत्य]/@deva[कृत्वा]/@deva[कारं] @deva[गतः]; @deva[पृष्ठतः] @deva[भूय]/@deva[भूत्वा]/@deva[भावं] @deva[तिष्ठति]. Without @deva[स्वाङ्ग]: @deva[सर्वतः] @deva[कृत्वा] @deva[गतः]. Without @deva[तस्]-affix: @deva[मुखीकृत्य] @deva[गतः], @deva[मुखीभूय] @deva[गतः]. The word @deva[प्रत्यय] in the sūtra ensures @deva[तस्] must be an affix—not a @deva[धातु]: @deva[मुखे] @deva[तस्यति] = @deva[मुखतः] (verbal form) doesn't qualify.",
            "advanced": "@deva[क्त्वा]/@deva[णमुल्] after @deva[कृ]/@deva[भू] with @deva[स्वाङ्ग] + @deva[तसिल्]/@deva[तसि] (@ref[5.3.78]ff.) @deva[उपपद]. @deva[यथासंख्य] (@ref[1.3.10]) is explicitly inapplicable—both pratyayas govern both dhātus. Examples: @deva[मुखतः] @deva[कृत्य]/@deva[कृत्वा]/@deva[कारं] @deva[गतः]; @deva[पृष्ठतः] @deva[भूय]/@deva[भूत्वा]/@deva[भावं] @deva[तिष्ठति]. Counter-examples: non-@deva[स्वाङ्ग] (@deva[सर्वतः] @deva[कृत्वा] @deva[गतः]); non-@deva[तस्]-affix (@deva[मुखीकृत्य], @deva[मुखीभूय]). @deva[प्रत्यय] in sūtra excludes verbal @deva[तस्]: @deva[मुखे] @deva[तस्यति] = @deva[मुखतः] (from @deva[तस्] 4P) doesn't trigger this rule."
        }
    },
    "34062": {
        "en": {
            "simple": "Both @deva[क्त्वा] and @deva[णमुल्] come after @deva[कृ] and @deva[भू] when compounded with: (1) words ending in the @deva[ना] affix (@deva[नाना] 'various', @deva[विना] 'without'—@ref[5.2.27]); (2) words ending in affixes with @deva[धा]-meaning (like @deva[धा], @deva[ध्यम्], @deva[धम्]—@ref[5.3.42]ff., added to numerals meaning 'fold/part'); (3) words with @deva[च्वि]-meaning (@ref[5.4.50]—'becoming what it wasn't before'). Examples: @deva[नाना] @deva[कृत्य]/@deva[कृत्वा]/@deva[नानाकारं] @deva[गतः] 'having made various, went'; @deva[विना] @deva[कृत्य]/@deva[कृत्वा]/@deva[कारं] @deva[गतः] 'having made without, went'; @deva[द्विधा]/@deva[द्वैधं] @deva[कृत्य]/@deva[कृत्वा]/@deva[कारं] @deva[गतः] 'having made twofold, went'. But @deva[हिरुक्] @deva[कृत्वा], @deva[पृथक्] @deva[कृत्वा] (words with @deva[ना]/@deva[धा] sense but not formed by those affixes) don't qualify.",
            "standard": "@deva[क्त्वा]/@deva[णमुल्] apply after @deva[कृ]/@deva[भू] with @deva[उपपद] ending in: (1) @deva[ना]-affix (@ref[5.2.27]): @deva[नाना], @deva[विना]; (2) @deva[धार्थ]-affix (@ref[5.3.42]–46): @deva[धा], @deva[ध्यम्], @deva[धम्], @deva[एधा] (added to numerals for 'fold/part'); (3) @deva[च्व्यर्थ] (@ref[5.4.50]): expressing 'becoming what wasn't before'. @deva[नाना]/@deva[विना] @deva[कृत्य]/@deva[कृत्वा]/@deva[कारं] @deva[गतः]; @deva[नाना]/@deva[विना] @deva[भूय]/@deva[भूत्वा]/@deva[भावं] @deva[गतः]; @deva[द्विधा]/@deva[द्वैधं] @deva[कृत्य]/etc. The sūtra uses @deva[प्रत्यय] to exclude words with mere @deva[ना]/@deva[धा] sense: @deva[हिरुक्] @deva[कृत्वा] ('except'), @deva[पृथक्] @deva[कृत्वा] ('separately'). @deva[अर्थ] qualifies @deva[धा] only (multiple @deva[धार्थ] affixes exist), not @deva[ना] (single affix). @ref[2.2.22] for optional @deva[समास].",
            "advanced": "@deva[क्त्वा]/@deva[णमुल्] after @deva[कृ]/@deva[भू] with: @deva[ना]-pratyayānta (@ref[5.2.27]: @deva[नाना], @deva[विना]); @deva[धार्थ]-pratyayānta (@ref[5.3.42]–46: @deva[धा], @deva[ध्यम्], @deva[धम्], @deva[एधा]); @deva[च्व्यर्थ] @deva[उपपद] (@ref[5.4.50]). Examples: @deva[नाना]/@deva[विना] @deva[कृत्य]/@deva[कृत्वा]/@deva[कारं]/@deva[भूय]/@deva[भूत्वा]/@deva[भावं] @deva[गतः]; @deva[द्विधा]/@deva[द्वैधं] + same forms. The term @deva[प्रत्यय] excludes words with mere @deva[ना]/@deva[धा] sense but different derivation: @deva[हिरुक्] @deva[कृत्वा], @deva[पृथक्] @deva[कृत्वा]. @deva[अर्थ] in @deva[नाधार्थ] qualifies @deva[धा] only (multiple @deva[धार्थ] pratyayas), not @deva[ना] (unique pratyaya @ref[5.2.27]). @deva[च्व्यर्थ] condition: @deva[नाना] @deva[कृत्वा] @deva[काष्ठानि] @deva[गतः] (literal 'various', not @deva[च्वि]-sense) uses only @deva[क्त्वा]. @ref[2.2.22] governs @deva[समास]."
        }
    },
    "34063": {
        "en": {
            "simple": "Both @deva[क्त्वा] and @deva[णमुल्] come after @deva[भू] 'to be' when compounded with @deva[तूष्णीम्] 'silently'. Examples: @deva[तूष्णीम्भूय], @deva[तूष्णीं] @deva[भूत्वा], @deva[तूष्णीम्भावम्] 'having become silent'. The sūtra repeats @deva[भू] to indicate that @deva[कृ] (from previous rules) no longer applies here.",
            "standard": "@deva[क्त्वा]/@deva[णमुल्] apply after @deva[भू] with @deva[तूष्णीम्] @deva[उपपद]. @deva[तूष्णीम्भूय]/@deva[तूष्णीं] @deva[भूत्वा]/@deva[तूष्णीम्भावम्] 'having become silent'. The repetition of @deva[भू] signals that @deva[कृ]'s @deva[अनुवृत्ति] from previous sūtras ceases entirely here.",
            "advanced": "@deva[भू] with @deva[तूष्णीम्] takes @deva[क्त्वा]/@deva[णमुल्]: @deva[तूष्णीम्भूय]/@deva[तूष्णीं] @deva[भूत्वा]/@deva[तूष्णीम्भावम्]. The explicit restatement of @deva[भू] terminates @deva[कृ]'s @deva[अनुवृत्ति] from @ref[3.4.59]ff."
        }
    },
    "34064": {
        "en": {
            "simple": "Both @deva[क्त्वा] and @deva[णमुल्] come after @deva[भू] when compounded with @deva[अन्वक्] meaning 'favorably disposed' (@deva[आनुलोम्य]). Examples: @deva[अन्वग्भूय], @deva[अन्वग्भूत्वा], @deva[अन्वग्] @deva[भावमास्ते] 'he is favorably disposed'. The @deva[आनुलोम्य] condition matters: @deva[अन्वग्भूत्वा] @deva[तिष्ठति] 'he remains behind' (spatial sense, not 'favorable')—here only @deva[क्त्वा] applies.",
            "standard": "@deva[भू] with @deva[अन्वक्] in the sense of @deva[आनुलोम्य] (being agreeable/favorably disposed) takes @deva[क्त्वा]/@deva[णमुल्]. @deva[अन्वग्भूय]/@deva[अन्वग्भूत्वा]/@deva[अन्वग्] @deva[भावमास्ते] 'he is favorably disposed'. The @deva[आनुलोम्य] condition distinguishes from literal/spatial uses: @deva[अन्वग्भूत्वा] @deva[तिष्ठति] 'remains behind' (only @deva[क्त्वा]).",
            "advanced": "@deva[भू] with @deva[अन्वक्] under @deva[आनुलोम्य] (favorable disposition, acting per another's wish) takes @deva[क्त्वा]/@deva[णमुल्]: @deva[अन्वग्भूय]/@deva[अन्वग्भूत्वा]/@deva[अन्वग्] @deva[भावमास्ते]. Without @deva[आनुलोम्य]: @deva[अन्वग्भूत्वा] @deva[तिष्ठति] 'stands behind' (spatial)—@deva[क्त्वा] only."
        }
    },
    "34065": {
        "en": {
            "simple": "The affix @deva[तुमुन्] (forming the infinitive) is added to any verb when the main verb has the sense of: @deva[शक्] 'to be able', @deva[धृष्] 'to dare', @deva[ज्ञा] 'to know', @deva[ग्लै] 'to be weary', @deva[घट्] 'to strive', @deva[रभ्] 'to begin', @deva[लभ्] 'to obtain', @deva[क्रम्] 'to proceed', @deva[सह्] 'to bear', @deva[अर्ह्] 'to deserve', or @deva[अस्] 'to be'. Example: @deva[शक्नोमि] @deva[भोक्तुम्] 'I am able to eat'. This differs from @ref[3.3.10] where the infinitive expresses purpose; here it expresses the complement of these verbs.",
            "standard": "@deva[तुमुन्] is added to a verb when the governing verb has the sense of @deva[शक्]/@deva[धृष्]/@deva[ज्ञा]/@deva[ग्लै]/@deva[घट्]/@deva[रभ्]/@deva[लभ्]/@deva[क्रम्]/@deva[सह्]/@deva[अर्ह्]/@deva[अस्]. Unlike @ref[3.3.10] (infinitive of purpose), here the infinitive has no purposive force—it complements the modal/auxiliary verb. @deva[शक्नोमि] @deva[भोक्तुम्] 'I can eat'; @deva[जानाति]/@deva[ग्लायति]/@deva[घटते]/@deva[आरभते]/@deva[लभते]/@deva[प्रक्रमते]/@deva[सहते]/@deva[अर्हति]/@deva[अस्ति]/@deva[भवति]/@deva[विद्यते] @deva[भोक्तुम्]. Per Bhaṭṭoji Dīkṣita, @deva[अर्थ] connects only with @deva[अस्]; but classical usage (Kālidāsa, etc.) shows synonyms of all these verbs also take infinitives.",
            "advanced": "@deva[तुमुन्] follows a @deva[धातु] when the @deva[अनुप्रयोग] has @deva[शक्]/@deva[धृष्]/@deva[ज्ञा]/@deva[ग्लै]/@deva[घट्]/@deva[रभ्]/@deva[लभ्]/@deva[क्रम्]/@deva[सह्]/@deva[अर्ह्]/@deva[अस्]-meaning. Distinguished from @ref[3.3.10]: here no @deva[तादर्थ्य] (purposive) sense; the @deva[अनुप्रयोग] is verbal @deva[उपपद]. Bhaṭṭoji's view: @deva[अर्थग्रहणमस्तिनैव] @deva[सम्बध्यते] @deva[अनन्तरत्वात्]—@deva[अर्थ] qualifies @deva[अस्] only, listing roots @deva[शक्]–@deva[अर्ह्] plus @deva[अस्]-synonyms. But classical evidence contradicts: @deva[न] @deva[पारयामि] @deva[निवेदयितुम्] (Śāk. 4), @deva[न] @deva[च] @deva[वेद] @deva[सम्यग्] @deva[द्रष्टुम्] (R. VI.30) show @deva[पारय]/@deva[विद्] (synonyms of @deva[शक्]/@deva[ज्ञा]) governing infinitives. Hence @deva[अर्थ] likely qualifies all listed roots."
        }
    },
    "34066": {
        "en": {
            "simple": "The affix @deva[तुमुन्] is added to a verb when @deva[अलम्] 'enough/capable' or a synonym expressing capability (@deva[पर्याप्ति]) is in construction. Examples: @deva[अलं] @deva[भोक्तुम्] 'capable of eating'; @deva[समर्थः] @deva[प्रोज्झितुम्] 'able to abandon'; @deva[पारयति] @deva[भोक्तुम्] 'is capable of eating'. The rule requires the @deva[पर्याप्ति] sense—so @deva[अलम्कृत्वा] (where @deva[अलम्] means 'enough' as adornment) doesn't apply.",
            "standard": "@deva[तुमुन्] follows a @deva[धातु] when @deva[अलम्] or an @deva[अलम्]-synonym (@deva[समर्थ], @deva[प्रवीण], @deva[कुशल], @deva[पटु], etc.) expressing @deva[पर्याप्ति] (capability) is compounded. @deva[अलं] @deva[भोक्तुम्]; @deva[कः] @deva[समर्थः] @deva[प्रोज्झितुम्] (Hitop.); @deva[अलं] @deva[दग्धुम्] @deva[लोकान्] (Kumāra. II.56); @deva[भोक्तुम्] @deva[प्रवीणः]/@deva[कुशलः]/@deva[पटुः]. Alternative reading: @deva[पर्याप्ति]/@deva[अलम्]/@deva[अलमर्थ]-word in @deva[उपपद] triggers @deva[तुमुन्]. Without @deva[पर्याप्ति] sense: @deva[अलम्कृत्वा] ('having adorned'). Note: @deva[शक्] (@ref[3.4.65]) differs from @deva[अलम्]-sense; with @deva[अलम्]-sense: @deva[शक्यमेवं] @deva[कर्तुम्].",
            "advanced": "@deva[तुमुन्] applies when @deva[अलम्] or @deva[अलमर्थ] (synonym expressing @deva[पर्याप्ति]) is @deva[उपपद]. Two interpretations: (1) @deva[अलम्] and its synonyms in @deva[पर्याप्ति]-sense; (2) the words @deva[पर्याप्ति], @deva[अलम्], or @deva[अलमर्थ]-synonyms. Examples: @deva[अलं] @deva[भोक्तुम्]; @deva[पर्याप्तो] @deva[भोक्तुम्]; @deva[भोक्तुम्] @deva[पारयति]. @deva[पर्याप्ति] condition excludes non-capability senses: @deva[अलम्कृत्वा]. @deva[शक्] in @ref[3.4.65] lacks @deva[अलम्]-sense there; with @deva[अलम्]-sense, this sūtra applies: @deva[शक्यमेवं] @deva[कर्तुम्]."
        }
    },
    "34067": {
        "en": {
            "simple": "The @deva[कृत्] affixes (verb-deriving suffixes) denote the agent (@deva[कर्तृ]) when no special sense is assigned elsewhere. Examples: @deva[कारकः] 'doer', @deva[कर्ता] 'maker', @deva[नन्दनः] 'one who causes joy', @deva[ग्राही] 'seizer', @deva[पचः] 'cook'. This default applies to affixes like @deva[ण्वुल्], @deva[तृच्] (@ref[3.1.133]), but not to affixes with specially assigned senses like @deva[ख्युन्] (@ref[3.2.5]–6).",
            "standard": "@deva[कृत्] affixes denote @deva[कर्तृ] (agent) as their default meaning. This @deva[उत्सर्ग] applies when no @deva[अपवाद] assigns a specific sense. @deva[कारकः] 'doer' (@deva[ण्वुल्]); @deva[कर्ता] 'agent' (@deva[तृच्]); @deva[नन्दनः] 'joy-causer'; @deva[ग्राही] 'seizer'; @deva[पचः] 'cook'. Doesn't apply to @deva[कृत्] affixes with assigned senses: @deva[ख्युन्] (@ref[3.2.5]–6), etc.",
            "advanced": "@deva[कृत्]-pratyayas denote @deva[कर्तृ] by default (@deva[उत्सर्ग]). Examples: @deva[कारकः] (@deva[ण्वुल्]), @deva[कर्ता] (@deva[तृच्] @ref[3.1.133]), @deva[नन्दनः], @deva[ग्राही], @deva[पचः]. Inapplicable to pratyayas with specific sense-assignments: @deva[ख्युन्] (@ref[3.2.5]–6), etc. This establishes the default @deva[कारकार्थ] for @deva[कृदन्त] formation."
        }
    },
    "34068": {
        "en": {
            "simple": "The words @deva[भव्य], @deva[गेय], @deva[प्रवचनीय], @deva[उपस्थानीय], @deva[जन्य], @deva[आप्लाव्य], and @deva[आपात्य] may optionally denote the agent, though they're formed with @deva[कृत्य] affixes (which normally denote object/action by @ref[3.4.70]). So @deva[गेय] can mean 'singer' (agent), 'song' (object), or 'singing' (action). Example: @deva[गेयो] @deva[माणवकः] @deva[साम्नाम्] 'the boy is the singer of the Sāmas' (agent) vs. @deva[गेयानि] @deva[माणवकेन] @deva[सामानि] 'the Sāmas ought to be sung by the boy' (object).",
            "standard": "These seven @deva[कृत्य]-formed words optionally denote @deva[कर्तृ] (agent), besides their regular @deva[भाव]/@deva[कर्मन्] senses (@ref[3.4.70]): @deva[भव्य] ('one who exists'/'existence'/'what exists'); @deva[गेय] ('singer'/'song'/'singing'); @deva[प्रवचनीय] ('explainer'/'explanation'/'what's to be explained'); @deva[उपस्थानीय] ('attendant'/'attendance'/'what's to be served'); @deva[जन्य] ('father'/'birth'/'what's born'); @deva[आप्लाव्य] ('immerser'/'immersion'/'what's immersed'); @deva[आपात्य] ('faller'/'falling'/'what falls'). Examples: @deva[गेयो] @deva[माणवकः] @deva[साम्नाम्] (agent); @deva[गेयानि] @deva[माणवकेन] @deva[सामानि] (object).",
            "advanced": "These @deva[कृत्यप्रत्ययान्त] words optionally take @deva[कर्तृ]-sense in addition to their default @deva[भाव]/@deva[कर्मन्] (@ref[3.4.70]): @deva[भव्य], @deva[गेय], @deva[प्रवचनीय], @deva[उपस्थानीय], @deva[जन्य], @deva[आप्लाव्य], @deva[आपात्य]. Triple meanings: @deva[गेय] = @deva[गायकः] (agent) / @deva[गानम्] (action) / @deva[गातव्यम्] (object). @deva[जन्य] = @deva[जायते] @deva[असौ] (agent: father) or @deva[जन्यमनेन] (object: what's born). Usage: @deva[गेयो] @deva[माणवकः] @deva[साम्नाम्] (agent); @deva[गेयानि] @deva[माणवकेन] @deva[सामानि] (object); @deva[उपस्थानीयोऽन्तेवासी] @deva[गुरोः] (agent) vs. @deva[उपस्थानीयः] @deva[शिष्येण] @deva[गुरुः] (object)."
        }
    },
    "34069": {
        "en": {
            "simple": "The @deva[ल]-affixes (the ten tense/mood markers: @deva[लट्], @deva[लिट्], @deva[लुट्], @deva[लृट्], @deva[लोट्], @deva[लेट्], @deva[लङ्], @deva[लिङ्], @deva[लुङ्], @deva[लृङ्]) denote the agent and the object. After intransitive verbs, they also denote the action (@deva[भाव]). In active voice, the affix marks the agent: @deva[गच्छति] @deva[देवदत्तः] 'Devadatta goes'. In passive of transitives, it marks the object: @deva[गम्यते] @deva[ग्रामो] @deva[देवदत्तेन] 'the village is gone to by Devadatta'. In passive of intransitives, it marks mere action (impersonal): @deva[आस्यते] @deva[देवदत्तेन] 'it is sat by Devadatta'.",
            "standard": "The @deva[ल]-pratyayas (all ten @deva[लकार]s) denote @deva[कर्तृ] and @deva[कर्मन्]; after @deva[अकर्मक] (intransitive) verbs, they also denote @deva[भाव] (action). The word @deva[च] draws @deva[कर्ता] from @ref[3.4.67]. After @deva[सकर्मक] verbs: active voice = @deva[कर्तृ] (@deva[गच्छति] @deva[देवदत्तः]); passive = @deva[कर्मन्] (@deva[गम्यते] @deva[ग्रामः] @deva[देवदत्तेन]). @deva[सकर्मक] verbs never denote @deva[भाव] (can't be used impersonally). After @deva[अकर्मक] verbs: @deva[आस्ते] @deva[देवदत्तः] (agent); @deva[आस्यते] @deva[देवदत्तेन] (impersonal @deva[भाव]).",
            "advanced": "@deva[ल]-pratyayas (collective term for @deva[लट्]–@deva[लृङ्], @deva[लः] being nominative plural of @deva[ल्]) denote @deva[कर्तृ] and @deva[कर्मन्]; @deva[अकर्मक]-@deva[धातु]s add @deva[भाव]. The @deva[च] draws @deva[कर्ता] via @deva[अनुवृत्ति] from @ref[3.4.67]. @deva[सकर्मक] @deva[धातु]s: @deva[कर्तरि] @deva[प्रयोग] = agent; @deva[कर्मणि] @deva[प्रयोग] = object. @deva[भाव] is impossible—transitives can't be impersonal. @deva[अकर्मक] @deva[धातु]s: active = @deva[कर्तृ] (@deva[आस्ते] @deva[देवदत्तः]); impersonal passive = @deva[भाव] (@deva[आस्यते] @deva[देवदत्तेन]). Böhtlingk: 'A finite verb expresses agent and object; intransitives additionally express impersonal action.'"
        }
    },
    "34070": {
        "en": {
            "simple": "The @deva[कृत्य] affixes (like @deva[तव्य], @deva[अनीयर्], @deva[य]), the @deva[क्त] affix, and affixes with @deva[खल्]-meaning (@ref[3.3.126]) denote only action (@deva[भाव]) and object (@deva[कर्मन्])—not the agent. Examples: @deva[कर्तव्यः] @deva[कटः] 'the mat must be made' (object); @deva[आशितव्यं] @deva[भवता] 'you must eat' (impersonal action); @deva[कृतः] @deva[कटः] 'the mat was made' (object); @deva[आसितं] @deva[भवता] 'you sat' (action); @deva[सुकरः] 'easy to make' (object).",
            "standard": "@deva[कृत्य]-pratyayas, @deva[क्त], and @deva[खलर्थ]-pratyayas (@ref[3.3.126]) denote @deva[भाव] and @deva[कर्मन्] only—@deva[एव] excludes @deva[कर्तृ]. @deva[कृत्य]: @deva[कर्तव्यः] @deva[कटः] (object); @deva[आशितव्यं] @deva[भवता] (@deva[भाव]—impersonal, neuter singular). @deva[क्त]: @deva[कृतः] @deva[कटः] (object); @deva[आसितं] @deva[भवता] (@deva[भाव]). @deva[खलर्थ]: @deva[ईषत्करः] @deva[कटः] (object); @deva[ईषदाढ्यंभवं] @deva[भवता] (@deva[भाव]). After @deva[सकर्मक] verbs, these affixes denote @deva[कर्मन्] only, never @deva[भाव].",
            "advanced": "@deva[कृत्य], @deva[क्त], and @deva[खलर्थ] pratyayas (@ref[3.3.126]) are restricted to @deva[तयोः] (@deva[भाव] and @deva[कर्मन्])—@deva[एव] excludes @deva[कर्तृ]. @deva[कृत्य] examples: @deva[कर्तव्यः] @deva[कटो] @deva[भवता] (@deva[कर्मन्]); @deva[आशितव्यं] @deva[भवता] (@deva[भाव]—neuter singular, genderless action). @deva[क्त]: @deva[कृतः] @deva[कटो] @deva[भवता] (@deva[कर्मन्]); @deva[आसितं] @deva[भवता] (@deva[भाव]). @deva[खलर्थ]: @deva[ईषत्करः]/@deva[सुकरः]/@deva[दुष्करः] @deva[कटः] (@deva[कर्मन्]); @deva[ईषदाढ्यंभवं] @deva[भवता] (@deva[भाव]). With @deva[सकर्मक] @deva[धातु]s, these denote @deva[कर्मन्] exclusively, never @deva[भाव] (impersonal usage blocked)."
        }
    },
    "34071": {
        "en": {
            "simple": "The @deva[क्त] affix also denotes the agent when the action has merely begun (@deva[आदिकर्मन्]). The word @deva[च] includes @deva[भाव] and @deva[कर्मन्] from the previous rule. Examples with @deva[प्र] + @deva[कृ]: @deva[प्रकृतः] @deva[कटं] @deva[देवदत्तः] 'Devadatta has begun making the mat' (agent); @deva[प्रकृतः] @deva[कटो] @deva[देवदत्तेन] 'the mat was begun by Devadatta' (object); @deva[प्रकृतं] @deva[देवदत्तेन] 'it was begun by Devadatta' (action).",
            "standard": "@deva[क्त] additionally denotes @deva[कर्तृ] when expressing @deva[आदिकर्मन्] (inchoative—action merely begun). The @deva[च] retains @deva[भाव]/@deva[कर्मन्] from @ref[3.4.70]. @deva[प्रकृतः] @deva[कटं] @deva[देवदत्तः] (@deva[कर्तृ]—'D. has begun the mat'); @deva[प्रकृतः] @deva[कटो] @deva[देवदत्तेन] (@deva[कर्मन्]); @deva[प्रकृतं] @deva[देवदत्तेन] (@deva[भाव]). Similarly @deva[प्रभुक्त] @deva[ओदनं] @deva[देवदत्तः] (agent); @deva[प्रभुक्त] @deva[ओदनो] @deva[देवदत्तेन] (object); @deva[प्रभुक्तं] @deva[देवदत्तेन] (act).",
            "advanced": "@deva[आदिकर्मन्] (inchoative sense—action at its inception) permits @deva[क्त] to denote @deva[कर्तृ] in addition to @deva[भाव]/@deva[कर्मन्] (@deva[च] retains @ref[3.4.70]). @deva[प्रकृतः] @deva[कटं] @deva[देवदत्तः] (@deva[कर्तरि] @deva[क्त]); @deva[प्रकृतः] @deva[कटो] @deva[देवदत्तेन] (@deva[कर्मणि]); @deva[प्रकृतं] @deva[देवदत्तेन] (@deva[भावे]). Same triple possibility: @deva[प्रभुक्तम्] @deva[ओदनं] @deva[देवदत्तः]/@deva[प्रभुक्त] @deva[ओदनो] @deva[देवदत्तेन]/@deva[प्रभुक्तं] @deva[देवदत्तेन]."
        }
    },
    "34072": {
        "en": {
            "simple": "The @deva[क्त] affix denotes agent, object, and action after: (1) verbs of motion (@deva[गत्यर्थ]), (2) intransitive verbs (@deva[अकर्मक]), and (3) the specific verbs @deva[श्लिष्] 'to embrace', @deva[शि] 'to lie', @deva[स्था] 'to stand', @deva[आस्] 'to sit', @deva[वस्] 'to dwell', @deva[जन्] 'to be born', @deva[रुह्] 'to mount', @deva[जृ] 'to age'. Examples: @deva[गतो] @deva[देवदत्तो] @deva[ग्रामम्] 'Devadatta has gone to the village' (agent); @deva[गतः] @deva[ग्रामो] @deva[देवदत्तेन] 'the village was gone to' (object); @deva[गतं] @deva[देवदत्तेन] 'going was done' (action).",
            "standard": "@deva[क्त] denotes @deva[कर्तृ], @deva[कर्मन्], and @deva[भाव] after: @deva[गत्यर्थ] (motion verbs), @deva[अकर्मक] (intransitives), and @deva[श्लिष्]/@deva[शि]/@deva[स्था]/@deva[आस्]/@deva[वस्]/@deva[जन्]/@deva[रुह्]/@deva[जृ]. @deva[च] draws @deva[भाव]/@deva[कर्मन्] from prior sūtras. Motion verbs: @deva[गतो] @deva[देवदत्तः] @deva[ग्रामम्] (agent); @deva[गतः] @deva[ग्रामः] @deva[देवदत्तेन] (object); @deva[गतं] @deva[देवदत्तेन] (act). Intransitives: @deva[ग्लानो] @deva[भवान्] (agent); @deva[ग्लानं] @deva[भवता] (act)—object impossible. The listed verbs @deva[श्लिष्] etc. become @deva[सकर्मक] with certain @deva[उपसर्ग]s, hence separate mention.",
            "advanced": "@deva[क्त] takes triple @deva[कारकार्थ] (@deva[कर्तृ], @deva[कर्मन्], @deva[भाव]) after @deva[गत्यर्थ], @deva[अकर्मक], and @deva[श्लिष्]/@deva[शि]/@deva[स्था]/@deva[आस्]/@deva[वस्]/@deva[जन्]/@deva[रुह्]/@deva[जृ]. @deva[गत्यर्थ] examples: @deva[गतो] @deva[देवदत्तो] @deva[ग्रामम्]/@deva[गतः] @deva[ग्रामो] @deva[देवदत्तेन]/@deva[गतं] @deva[देवदत्तेन]. @deva[अकर्मक]: agent/@deva[भाव] only (no object)—@deva[ग्लानो] @deva[भवान्]/@deva[ग्लानं] @deva[भवता]. The eight listed @deva[धातु]s are inherently @deva[अकर्मक] but become @deva[सकर्मक] with certain @deva[उपसर्ग]s, necessitating separate enumeration: @deva[उपश्लिष्टो] @deva[गुरुम्] @deva[भवान्] (agent), @deva[उपश्लिष्टो] @deva[गुरुः] @deva[भवता] (object), @deva[उपश्लिष्टं] @deva[भवता] (act). Full paradigms for @deva[उपशि], @deva[उपस्था], @deva[उपास्], @deva[अनुवस्], @deva[अनुजन्], @deva[आरुह्], @deva[अनुजृ] follow the same pattern."
        }
    },
    "34073": {
        "en": {
            "simple": "The words @deva[दाश] and @deva[गोघ्न] are irregular formations where the @deva[कृत्] affix denotes the recipient (@deva[सम्प्रदान]), not the agent. @deva[दाश] (from @deva[दाशृ] 'to give' + @deva[अच्] by @ref[3.1.134]) means 'one to whom something is given'—a servant. @deva[गोघ्न] means 'one for whom a cow is killed'—a guest (not 'cow-killer'). Thus @deva[दाशः] = @deva[दाशन्ति] @deva[तस्मै] 'they give to him'; @deva[गोघ्नः] = @deva[तस्मै] @deva[दातुं] @deva[गां] @deva[घ्नन्ति] 'they kill a cow to give to him'.",
            "standard": "@deva[दाश] and @deva[गोघ्न] are irregular @deva[कृदन्त]s denoting @deva[सम्प्रदान] (recipient) instead of @deva[कर्तृ] (@ref[3.4.67]). @deva[दाश] = @deva[दाशृ] + @deva[अच्] (@ref[3.1.134]): 'one to whom they give' = servant. @deva[गोघ्न]: not 'cow-slayer' but 'one for whose arrival a cow is slaughtered' = guest. This irregular @deva[गोघ्न] applies to priests, guests, sons-in-law; the regular @deva[गोघ्न] ('cow-killer') denotes a @deva[चण्डाल]. @deva[दाशः] = @deva[दाशन्ति] @deva[तस्मै]; @deva[गोघ्नः] = @deva[तस्मै] @deva[दातुं] @deva[गां] @deva[घ्नन्ति].",
            "advanced": "@deva[दाश]/@deva[गोघ्न] are @deva[निपातन]-forms where @deva[कृत्] denotes @deva[सम्प्रदान] rather than default @deva[कर्तृ] (@ref[3.4.67]). @deva[दाश]: @deva[दाशृ] + @deva[अच्] (@ref[3.1.134]) = @deva[दाशन्ति] @deva[तस्मै] 'servant/recipient'. @deva[गोघ्न]: @deva[तस्मै] @deva[दातुं] @deva[गां] @deva[घ्नन्ति] 'guest' (cow killed for his sake)—applicable to @deva[ऋत्विज्], @deva[अतिथि], @deva[जामातृ], etc. Distinguished from regular @deva[गोघ्न] (= @deva[गां] @deva[हन्ति], agent-sense = cow-killer/@deva[चण्डाल])."
        }
    },
    "34074": {
        "en": {
            "simple": "The words in the @deva[भीमादि] list are irregular formations that denote @deva[अपादान] (ablation—the source from which something moves away). These are formed by @deva[उणादि] affixes: @deva[भीम] (@deva[भी] + @deva[मक्]), @deva[भीष्म] (@deva[भी] + @deva[षुक्] + @deva[मक्]), etc. Normally @deva[उणादि] words don't denote recipient or ablation (@ref[3.4.75]), but this rule makes an exception for these words. The list includes: @deva[भीम], @deva[भीष्म], @deva[भयानक], @deva[वरु], @deva[चरु], @deva[भूमि], @deva[रजस्], @deva[संस्कार], @deva[सङ्क्रन्दन], @deva[प्रपतन], @deva[समुद्र], @deva[स्रुच्]/\n@deva[स्रुव], @deva[स्रज्], @deva[खलति].",
            "standard": "@deva[भीमादि] words (formed by @deva[उणादि] affixes) irregularly denote @deva[अपादान]. @deva[भीम]: @deva[भी] + @deva[मक्] (Uṇ. I.145); @deva[भीष्म]: @deva[भी] + @deva[षुक्] + @deva[मक्] (Uṇ. I.148). By @ref[3.4.75], @deva[उणादि] words normally exclude @deva[सम्प्रदान]/@deva[अपादान]; this sūtra excepts @deva[भीमादि]. The @deva[गण] includes: @deva[भीम], @deva[भीष्म], @deva[भयानक] (Uṇ. III.82), @deva[वरु], @deva[चरु] (Uṇ. I.7), @deva[भूमि] (Uṇ. IV.45), @deva[रजस्] (Uṇ. IV.217), @deva[संस्कार], @deva[सङ्क्रन्दन], @deva[प्रपतन], @deva[समुद्र], @deva[स्रुच्]/@deva[स्रुव] (Uṇ. II.61), @deva[स्रज्] (Uṇ. II.62), @deva[खलति].",
            "advanced": "@deva[भीमादि] @deva[गण] (formed by @deva[उणादि] pratyayas) takes @deva[अपादान]-sense, excepted from @ref[3.4.75]'s exclusion of @deva[सम्प्रदान]/@deva[अपादान] for @deva[उणादि] formations. Derivations: @deva[भीम] = @deva[भी] + @deva[मक्] (Uṇ. I.145.148); @deva[भीष्म] = @deva[भी] + @deva[षुक्] + @deva[मक्] (Uṇ. I.148). Complete @deva[गण]: @deva[भीम], @deva[भीष्म], @deva[भयानक] (Uṇ. III.82), @deva[वरु], @deva[चरु] (Uṇ. I.7), @deva[भूमि] (Uṇ. IV.45), @deva[रजस्] (Uṇ. IV.217), @deva[संस्कार], @deva[सङ्क्रन्दन], @deva[प्रपतन], @deva[समुद्र], @deva[स्रुच्]/@deva[स्रुव] (Uṇ. II.61), @deva[स्रज्] (Uṇ. II.62), @deva[खलति]."
        }
    },
    "34075": {
        "en": {
            "simple": "Words formed by @deva[उणादि] affixes denote meanings other than @deva[सम्प्रदान] (recipient) and @deva[अपादान] (source). Since @deva[उणादि] affixes are a type of @deva[कृत्], they would normally denote agent (@ref[3.4.67]). This rule extends their meaning to include object (@deva[कर्मन्]), instrument (@deva[करण]), and location (@deva[अधिकरण]). Examples: @deva[कृषि] 'agriculture' (what is ploughed—object); @deva[तन्तु] 'thread' (what is stretched—object); @deva[वर्त्म] 'path' (where one goes—location); @deva[चर्म] 'skin' (where one lives—location).",
            "standard": "@deva[उणादि] pratyayas (being @deva[कृत्]) would denote @deva[कर्तृ] by @ref[3.4.67]. This sūtra specifies they denote @deva[कारक]s other than @deva[सम्प्रदान] and @deva[अपादान]—i.e., @deva[कर्मन्], @deva[करण], @deva[अधिकरण] (besides @deva[कर्तृ]). @deva[ताभ्याम्] 'other than those two' includes @deva[सम्प्रदान] by implication (had it been @deva[अन्यत्रोणादयः], only nearest @deva[अपादान] would be excluded). Examples: @deva[कृषि] (Uṇ. IV.120) = object; @deva[तन्तु] (Uṇ. I.69) = object; @deva[वर्त्म] (Uṇ. IV.145) = location; @deva[चर्म] (Uṇ. IV.145) = location.",
            "advanced": "@deva[उणादि] pratyayas, being @deva[कृत्]-subdivision, would take @deva[कर्तृ]-sense (@ref[3.4.67]). This sūtra permits @deva[कर्मन्], @deva[करण], @deva[अधिकरण]—everything except @deva[सम्प्रदान]/@deva[अपादान]. The dual @deva[ताभ्याम्] (not singular @deva[अन्यत्र]) ensures both @deva[सम्प्रदान] and @deva[अपादान] are excluded (singular would exclude only nearest @deva[अपादान]). Examples: @deva[कृषि] (Uṇ. IV.120) = @deva[कृषितोऽसौ] (@deva[कर्मन्]); @deva[तन्तु] (Uṇ. I.69) = @deva[तन्यते] @deva[इति] (@deva[कर्मन्]); @deva[वर्त्म] (Uṇ. IV.145) = @deva[वृत्तम्] (@deva[अधिकरण]); @deva[चर्म] (Uṇ. IV.145) = @deva[चरितम्] (@deva[अधिकरण]—'in which they live')."
        }
    }
}

for sutra_id, content in updates.items():
    commentary[sutra_id] = content

with open('static/data/layered_commentary.json', 'w', encoding='utf-8') as f:
    json.dump(commentary, f, ensure_ascii=False, indent=2)

print("Updated commentary for sutras 3.4.61-3.4.75 (Batch 5)")
