#!/usr/bin/env python3
"""Rewrite commentary for sūtras 4.3.106-120."""

import json


def load_json(path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)

def save_json(path, data):
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

def main():
    commentary_path = 'static/data/layered_commentary.json'
    data = load_json(commentary_path)

    updates = {
        "43106": {
            "en": {
                "simple": "The affix @deva[णिनि] comes in the @deva[प्रोक्त] (enounced) sense after words in the @deva[शौनकादि] list when referring to Vedic literature (@deva[छन्दस्]). This overrides @deva[छ] and @deva[अण्].\n\n**Examples:**\n- @deva[शौनकेन प्रोक्तम् अधीयते] → @deva[शौनकिनः] 'those who study the Veda taught by Śaunaka'\n- @deva[वाजसनेयिनः] (students of Vājasaneya's teaching)\n\nWhy 'Vedic literature'? For non-Vedic works: @deva[शौनकीया शिक्षा] 'the phonetics manual of Śaunaka' (uses @deva[छ], not @deva[णिनि]).\n\nNote: @deva[कठशाठ] in this list must be taken as a compound. For @deva[कठ] alone, the affix is elided by the next rule.\n\n**@deva[शौनकादि] list:** @deva[शौनक], @deva[वाजसनेय], @deva[शार्ङ्गरव], @deva[शापेय], @deva[शाष्पेय], @deva[खाडायन], @deva[स्तम्भ], @deva[स्कन्ध], @deva[देवदर्शन], @deva[रज्जुभार], @deva[रज्जुकण्ठ], @deva[कठशाठ], @deva[कषाय], @deva[तल], @deva[दण्ड], @deva[पुरुषांसक], @deva[अश्वपेज], @deva[साङ्गरव], @deva[स्कन्द], @deva[देवदत्तशठ], @deva[तलवकार].",
                "standard": "The affix @deva[णिनि] comes after @deva[शौनकादि] words in the @deva[प्रोक्त] sense when the reference is to @deva[छन्दस्] (Vedic texts). This debars @deva[छ] and @deva[अण्].\n\n**Examples:** @deva[शौनकिनः] (students of Śaunaka's Vedic teaching), @deva[वाजसनेयिनः]\n\n**Restriction to @deva[छन्दस्]:** @deva[शौनकीया शिक्षा] (Śaunaka's phonetics, a non-@deva[छन्दस्] work) uses @deva[छ].\n\n**@deva[कठशाठ]:** Must be taken as a compound → @deva[काठशाठिनः]. For @deva[कठ] alone, see @ref[4.3.107].\n\n**@deva[शौनकादि] गण:** @deva[शौनक], @deva[वाजसनेय], @deva[शार्ङ्गरव], @deva[शापेय]/​@deva[सांपेय], @deva[शाष्पेय]/​@deva[शाखेय], @deva[खाडायन], @deva[स्तम्भ]/​@deva[स्कम्भ], @deva[स्कन्ध], @deva[देवदर्शन], @deva[रज्जुभार], @deva[रज्जुकण्ठ], @deva[कठशाठ], @deva[कषाय]/​@deva[कशाय], @deva[तल], @deva[दण्ड], @deva[पुरुषांसक]/​@deva[पुरुषासक], @deva[अश्वपेज]/​@deva[अश्वपेठा], @deva[साङ्गरव], @deva[स्कन्द], @deva[देवदत्तशठ], @deva[तलवकार].",
                "advanced": "This @deva[सूत्र] teaches @deva[णिनि] after @deva[शौनकादि] words in the @deva[प्रोक्त] sense, qualified by @deva[छन्दसि] (for Vedic literature). It debars @deva[छ] and @deva[अण्].\n\n**Examples:** @deva[शौनकेन प्रोक्तम् अधीयते] → @deva[शौनकिनः]; @deva[वाजसनेयिनः]\n\n**@deva[छन्दसि] restriction:** For @deva[शिक्षा] (non-@deva[छन्दस्]): @deva[शौनकीया शिक्षा]\n\n**@deva[कठशाठ]:** Treated as @deva[द्वन्द्व] → @deva[काठशाठिनः]. For @deva[कठ] alone, @deva[लुक्] by @ref[4.3.107].\n\n**@deva[शौनकादि] गण (21):** @deva[शौनक], @deva[वाजसनेय], @deva[शार्ङ्गरव], @deva[शापेय] (@deva[सांपेय]), @deva[शाष्पेय] (@deva[शाखेय]), @deva[खाडायन], @deva[स्तम्भ] (@deva[स्कम्भ]), @deva[स्कन्ध], @deva[देवदर्शन], @deva[रज्जुभार], @deva[रज्जुकण्ठ], @deva[कठशाठ], @deva[कषाय] (@deva[कशाय]), @deva[तल], @deva[दण्ड], @deva[पुरुषांसक] (@deva[पुरुषासक]), @deva[अश्वपेज] (@deva[अश्वपेठा]), @deva[साङ्गरव], @deva[स्कन्द], @deva[देवदत्तशठ], @deva[तलवकार]."
            }
        },
        "43107": {
            "en": {
                "simple": "The affix denoting 'enounced by him' is deleted (@deva[लुक्]) after the words @deva[कठ] and @deva[चरक].\n\n@deva[कठ] would normally take @deva[णिनि] (as a pupil of Vaiśampāyana), and @deva[चरक] would take @deva[अण्]. Both affixes are elided.\n\n**Examples:**\n- @deva[कठाः] 'those who study the Veda taught by Kaṭha' (no affix visible)\n- @deva[चरकाः] 'those who study the teaching of Caraka'\n\nThis applies only to Vedic works. For secular verses: @deva[काठाः श्लोकाः], @deva[चारकाः श्लोकाः] (with regular affixes).",
                "standard": "The @deva[प्रोक्त]-sense affix undergoes @deva[लुक्] (deletion) after @deva[कठ] and @deva[चरक].\n\n@deva[कठ] would take @deva[णिनि] by @ref[4.3.104] (as @deva[वैशम्पायनान्तेवासी]); @deva[चरक] would take @deva[अण्]. Both are elided.\n\n**Examples:** @deva[कठाः], @deva[चरकाः] (students of their respective Vedic teachings)\n\n**@deva[छन्दसि] restriction:** For @deva[श्लोक] (secular verses): @deva[काठाः श्लोकाः], @deva[चारकाः श्लोकाः]—regular affixes apply.",
                "advanced": "This @deva[सूत्र] ordains @deva[लुक्] of the @deva[प्रोक्त]-sense affix after @deva[कठ] and @deva[चरक].\n\n@deva[कठ] is a @deva[वैशम्पायनान्तेवासी], hence would take @deva[णिनि] by @ref[4.3.104]. @deva[चरक] would take @deva[अण्] by @ref[4.1.83].\n\n**Examples:** @deva[कठाः], @deva[चरकाः]\n\n**@deva[छन्दसि] continues:** The @deva[लुक्] applies only in @deva[छन्दस्] context. For @deva[श्लोक]: @deva[काठाः श्लोकाः], @deva[चारकाः श्लोकाः]."
            }
        },
        "43108": {
            "en": {
                "simple": "The affix @deva[अण्] comes in the @deva[प्रोक्त] (enounced) sense after the word @deva[कलापिन्]. This overrides @deva[णिनि] that would come by the earlier rule.\n\n**Example:** @deva[कलापाः] 'those who study the work taught by Kalāpin'\n\n**Derivation:** @deva[कलापिन्] + @deva[अण्]. The @deva[इन्] ending is deleted before the affix. Normally @ref[6.4.164] would prevent this deletion before non-patronymic @deva[अण्], but a special rule (@deva[वार्त्तिक]) requires deletion of the @deva[टि] portion for words like @deva[कलापिन्], @deva[कुथुमिन्], @deva[तैतिलिन्], etc., when a @deva[तद्धित] follows.\n\nResult: @deva[कलापिन्] → @deva[कलाप] + @deva[अण्] → @deva[कालाप] → @deva[कलापाः] (nominative plural).",
                "standard": "The affix @deva[अण्] comes after @deva[कलापिन्] in the @deva[प्रोक्त] sense, debarring @deva[णिनि] of @ref[4.3.104].\n\n**Example:** @deva[कलापाः]\n\n**Derivation:** @deva[कलापिन्] + @deva[अण्]. By @ref[6.4.144], @deva[इन्] should be deleted before @deva[तद्धित]. Though @ref[6.4.164] would prevent this for non-patronymic @deva[अण्], a @deva[वार्त्तिक] overrides:\n\n@deva[टि]-deletion applies to: @deva[सब्रह्मचारिन्], @deva[पीठसर्पिन्], @deva[कलापिन्], @deva[कुथुमिन्], @deva[तैतिलिन्], @deva[जाजलिन्], @deva[जाङ्गलिन्], @deva[लाङ्गलिन्], @deva[शिलालिन्], @deva[शिखण्डिन्], @deva[सूकरसद्मन्], @deva[सुपर्वण्].\n\nThus: @deva[कलापिन्] → @deva[कलाप] + @deva[अण्] → @deva[कलापाः].",
                "advanced": "This @deva[सूत्र] prescribes @deva[अण्] after @deva[कलापिन्] in the @deva[प्रोक्त] sense, as @deva[अपवाद] to @deva[णिनि] of @ref[4.3.104].\n\n**Example:** @deva[कलापाः]\n\n**Derivation:** @deva[कलापिन्] + @deva[अण्]\n\nBy @ref[6.4.144], @deva[इन्] of @deva[कलापिन्] should delete before @deva[तद्धित]. However, @ref[6.4.164] blocks deletion when non-@deva[अपत्य]-denoting @deva[अण्] follows @deva[इन्]-ending words.\n\n**Vārtika:** @deva[टि]-deletion before @deva[तद्धित] for: @deva[सब्रह्मचारिन्], @deva[पीठसर्पिन्], @deva[कलापिन्], @deva[कुथुमिन्], @deva[तैतिलिन्], @deva[जाजलिन्], @deva[जाङ्गलिन्], @deva[लाङ्गलिन्], @deva[शिलालिन्], @deva[शिखण्डिन्], @deva[सूकरसद्मन्], @deva[सुपर्वण्].\n\nThus @deva[ईन्] is deleted: @deva[कलाप] + @deva[अण्] → @deva[कलापाः]."
            }
        },
        "43109": {
            "en": {
                "simple": "The affix @deva[ढिनुक्] comes in the @deva[प्रोक्त] (enounced) sense after the word @deva[छगलिन्]. This overrides the @deva[णिनि] that would come by the pupil-of-Kalāpin rule.\n\n**Example:** @deva[छागलेयिनः] 'those who study the Vedic teaching of Chagalin'\n\n@deva[छगलिन्] is a pupil of @deva[कलापिन्] and would normally take @deva[णिनि] by @ref[4.3.104], but this rule substitutes @deva[ढिनुक्].",
                "standard": "The affix @deva[ढिनुक्] comes after @deva[छगलिन्] in the @deva[प्रोक्त] sense, debarring @deva[णिनि] of @ref[4.3.104].\n\n@deva[छगलिन्] is a @deva[कलाप्यन्तेवासी] (pupil of Kalāpin).\n\n**Example:** @deva[छागलेयिनः]",
                "advanced": "This @deva[सूत्र] prescribes @deva[ढिनुक्] after @deva[छगलिन्] in the @deva[प्रोक्त] sense, as @deva[अपवाद] to @deva[णिनि] of @ref[4.3.104] (for @deva[कलाप्यन्तेवासी] words).\n\n**Example:** @deva[छागलेयिनः]"
            }
        },
        "43110": {
            "en": {
                "simple": "The affix @deva[णिनि] comes in the @deva[प्रोक्त] (enounced) sense after @deva[पाराशर्य] and @deva[शिलालिन्], specifically for the @deva[भिक्षुसूत्र] (treatise on mendicants' duties) and @deva[नटसूत्र] (treatise on dancers/performers).\n\n**Examples:**\n- @deva[पाराशर्य] + @deva[णिनि] → @deva[पाराशरिणः] 'those who study the mendicants' manual taught by Pārāśarya'\n- @deva[शिलालिन्] + @deva[णिनि] → @deva[शैलालिनः] 'those who study the performers' manual taught by Śailālin'\n\nThese treatises are treated metaphorically as @deva[छन्दस्] (Vedic texts).\n\nWhy 'for these specific treatises'? For other works: @deva[पाराशरम्], @deva[शैलालम्] (with different affixes).",
                "standard": "The affix @deva[णिनि] comes after @deva[पाराशर्य] and @deva[शिलालिन्] in the @deva[प्रोक्त] sense when referring to @deva[भिक्षुसूत्र] and @deva[नटसूत्र] respectively.\n\n**Examples:**\n- @deva[पाराशरिणः भिक्षवः] 'mendicants who study Pārāśarya's treatise'\n- @deva[शैलालिनः नटाः] 'performers who study Śailālin's treatise'\n\nDerivation of @deva[पाराशरिन्]: @deva[पाराशर्य] + @deva[णिनि] → @deva[पाराशर] + @deva[णिनि] (@ref[6.4.152]) → @deva[पाराशरिन्]\n\nThese works are treated as @deva[छन्दस्] metaphorically. The @deva[तद्विषय] sense (@ref[4.2.66]) also applies.\n\n**Restriction:** For other works by these authors: @deva[पाराशरम्], @deva[शैलालम्].",
                "advanced": "This @deva[सूत्र] teaches @deva[णिनि] (not @deva[ढिनुक्] from preceding context) after @deva[पाराशर्य] and @deva[शिलालिन्] in the @deva[प्रोक्त] sense, restricted to @deva[भिक्षुसूत्र] and @deva[नटसूत्र].\n\n**Examples:** @deva[पाराशरिणः भिक्षवः], @deva[शैलालिनः नटाः]\n\n**Derivation:** @deva[पाराशर्य] + @deva[णिनि] → @deva[पाराशर] + @deva[इन्] by @ref[6.4.152] (@deva[य] deletion) → @deva[पाराशरिन्]\n\nThese @deva[सूत्र]s are @deva[उपचारेण छन्दस्] (metaphorically Vedic). The @deva[तद्विषय] relation (@ref[4.2.66]) also holds: @deva[पाराशरिणः] = 'students of Pārāśarya's @deva[भिक्षुसूत्र].'\n\nSome hold this expresses only @deva[तद्विषयता], never @deva[प्रोक्त] alone.\n\n**Counter-examples (other works):** @deva[पाराशरम्], @deva[शैलालम्]."
            }
        },
        "43111": {
            "en": {
                "simple": "The affix @deva[इनि] (without @deva[ण्]) comes in the @deva[प्रोक्त] (enounced) sense after @deva[कर्मन्द] and @deva[कृशाश्व], specifically for the @deva[भिक्षुसूत्र] (mendicants' treatise) and @deva[नटसूत्र] (performers' treatise).\n\n**Examples:**\n- @deva[कर्मन्दिनः भिक्षवः] 'mendicants who study Karmandin's treatise'\n- @deva[कृशाश्विनः नटाः] 'performers who study Kṛśāśvin's treatise'\n\nFor other works by these authors: @deva[कार्मन्दकम्], @deva[कार्शाश्वम्] (with @deva[अण्]).",
                "standard": "The affix @deva[इनि] comes after @deva[कर्मन्द] and @deva[कृशाश्व] in the @deva[प्रोक्त] sense for @deva[भिक्षुसूत्र] and @deva[नटसूत्र].\n\n**Examples:** @deva[कर्मन्दिनः भिक्षवः], @deva[कृशाश्विनः नटाः]\n\nThe @deva[तद्विषय] sense (@ref[4.2.66]) also applies.\n\n**For other works:** @deva[कार्मन्दकम्], @deva[कार्शाश्वम्] (with @deva[अण्]).",
                "advanced": "This @deva[सूत्र] teaches @deva[इनि] (not @deva[णिनि]) after @deva[कर्मन्द] and @deva[कृशाश्व] in the @deva[प्रोक्त] sense, restricted to @deva[भिक्षुसूत्र] and @deva[नटसूत्र].\n\n**Examples:** @deva[कर्मन्दिनः भिक्षवः], @deva[कृशाश्विनः नटाः]\n\nThe @deva[तद्विषय] sense (@ref[4.2.66]) is inherent. For other works: @deva[कार्मन्दकम्], @deva[कार्शाश्वम्]."
            }
        },
        "43112": {
            "en": {
                "simple": "An affix (from the @deva[प्राग्दीव्यतोऽण्] set, @ref[4.1.83]) comes after a word in the instrumental case to mean 'in the same direction as that.'\n\nThe phrase @deva[एकदिक्] means 'having a common direction' (@deva[तुल्यदिक्]).\n\n**Examples:**\n- @deva[सुदाम्ना एकदिक्] → @deva[सौदामनी विद्युत्] 'lightning (that goes) in the same direction as the Sudāman mountain'\n- @deva[हैमवती] 'in the same direction as Himavat'\n- @deva[त्रैककुदी], @deva[पैलुमूली]\n\nNote: The repetition of @deva[तेन] in this rule (though available from @ref[4.3.101]) indicates that the @deva[छन्दस्] context governing the previous ten rules does not continue here. Thus @deva[तद्विषयता] (@ref[4.2.66]) does not apply.",
                "standard": "An affix from @deva[प्राग्दीव्यतोऽण्] (@ref[4.1.83]) comes after a word in @deva[तृतीया] in the sense of @deva[एकदिक्] (same direction, @deva[तुल्यदिक्]).\n\n**Examples:** @deva[सुदाम्ना एकदिक्] → @deva[सौदामनी विद्युत्]; @deva[हैमवती], @deva[त्रैककुदी], @deva[पैलुमूली]\n\n**Technical note:** The explicit @deva[तेन] (though available by @deva[अनुवृत्ति] from @ref[4.3.101]) signals that @deva[छन्दसि] from the preceding ten @deva[सूत्र]s does not continue. Consequently, @deva[तद्विषयता] (@ref[4.2.66]) does not apply here.",
                "advanced": "This @deva[सूत्र] introduces the @deva[एकदिक्] (common direction) sense for @deva[प्राग्दीव्यतोऽण्] affixes (@ref[4.1.83]), with the base in @deva[तृतीया].\n\n@deva[एकदिक्] = @deva[तुल्यदिक्] (same direction).\n\n**Examples:** @deva[सौदामनी विद्युत्] (lightning in Sudāman's direction), @deva[हैमवती], @deva[त्रैककुदी], @deva[पैलुमूली]\n\n**@deva[तेन] repetition:** Though @deva[तेन] could come by @deva[अनुवृत्ति] from @ref[4.3.101], its explicit statement indicates @deva[छन्दसि] from the preceding ten @deva[सूत्र]s (@ref[4.3.102]–@ref[4.3.111]) does not continue. Hence @deva[तद्विषयता] (@ref[4.2.66]) is inapplicable."
            }
        },
        "43113": {
            "en": {
                "simple": "The affix @deva[तसि] also comes in the sense of 'in the same direction as that.' This is in addition to @deva[अण्] and the other affixes.\n\nWords formed with @deva[तसि] are indeclinable (@deva[अव्यय]) by @ref[1.1.37].\n\n**Examples:**\n- @deva[हिमवतः] 'in the same direction as Himavat'\n- @deva[पीलुमूलतः], @deva[सुदामतः]",
                "standard": "The affix @deva[तसि] comes in the @deva[एकदिक्] sense, in addition to @deva[अण्] etc.\n\nWords with @deva[तसि] are @deva[अव्यय] by @ref[1.1.37].\n\n**Examples:** @deva[हिमवतः], @deva[पीलुमूलतः], @deva[सुदामतः]",
                "advanced": "This @deva[सूत्र] adds @deva[तसि] to the @deva[एकदिक्] sense, alongside @deva[अण्] etc. from @ref[4.3.112].\n\n@deva[तस्यादिति] affixes are @deva[अव्यय] by @ref[1.1.37].\n\n**Examples:** @deva[हिमवतः], @deva[पीलुमूलतः], @deva[सुदामतः]"
            }
        },
        "43114": {
            "en": {
                "simple": "The affixes @deva[यत्] and @deva[तसि] come in the sense of 'in the same direction as that' after the word @deva[उरस्].\n\n**Examples:**\n- @deva[उरसा एकदिक्] → @deva[उरस्य] (with @deva[यत्])\n- @deva[उरसा एकदिक्] → @deva[उरस्तः] (with @deva[तसि])\n\nThe @deva[च] in the rule includes @deva[तसि] from the previous rule.",
                "standard": "The affixes @deva[यत्] and @deva[तसि] come after @deva[उरस्] in the @deva[एकदिक्] sense.\n\n**Examples:** @deva[उरस्य], @deva[उरस्तः]\n\nThe @deva[च] draws @deva[तसि] from @ref[4.3.113].",
                "advanced": "This @deva[सूत्र] prescribes @deva[यत्] after @deva[उरस्] in the @deva[एकदिक्] sense. The @deva[च] includes @deva[तसि] from @ref[4.3.113].\n\n**Examples:** @deva[उरस्य], @deva[उरस्तः]"
            }
        },
        "43115": {
            "en": {
                "simple": "An affix (from the @deva[प्राग्दीव्यतोऽण्] set) comes after a word in the instrumental case to mean 'discovered by him.'\n\nThe word @deva[उपज्ञात] means knowledge discovered by oneself without being taught—an intuition or self-taught discovery.\n\n**Examples:**\n- @deva[पाणिनिना उपज्ञातम्] → @deva[पाणिनीयम् अकालकं व्याकरणम्] 'the grammar discovered by Pāṇini'\n- @deva[काशकृत्स्नम् गुरुलाघवम्] 'the science of weights (or economics) discovered by Kāśakṛtsna'\n- @deva[आपिशलम् दुष्करणम्] 'the work called Duṣkaraṇa discovered by Āpiśala'\n\nPāṇini's grammar is called @deva[अकालक] because it doesn't define tenses (@deva[काल]). @deva[गुरुलाघव] is the science of weighing options. @deva[दुष्करण] is a grammar named after its technical term @deva[दुषू].",
                "standard": "An affix from @deva[प्राग्दीव्यतोऽण्] (@ref[4.1.83]) comes after a word in @deva[तृतीया] in the @deva[उपज्ञात] (discovered) sense.\n\n@deva[उपज्ञात] = knowledge acquired by oneself without being taught; intuition or original discovery.\n\n**Examples:**\n- @deva[पाणिनीयम् अकालकं व्याकरणम्] (Pāṇini's grammar)\n- @deva[काशकृत्स्नम् गुरुलाघवम्] (Kāśakṛtsna's work on weighing methods)\n- @deva[आपिशलम् दुष्करणम्] (Āpiśala's grammar)\n\n**Terminology:**\n- @deva[अकालक]: doesn't define @deva[काल] (tenses)\n- @deva[गुरुलाघव]: science of weighing options (@deva[यत्र उपायानां गौरवं लाघवं च चिन्त्यते])\n- @deva[दुष्करण]: named for its technical term @deva[दुषू]; some say it means @deva[कामशास्त्र]\n\nCompare @ref[2.4.21].",
                "advanced": "This @deva[सूत्र] introduces the @deva[उपज्ञात] sense for @deva[प्राग्दीव्यतोऽण्] affixes (@ref[4.1.83]), with the base in @deva[तृतीया].\n\n@deva[उपज्ञात] = self-discovered knowledge (intuition), as opposed to @deva[प्रोक्त] (transmitted teaching) or @deva[कृत] (composed work).\n\n**Examples:**\n- @deva[पाणिनीयम् अकालकं व्याकरणम्]\n- @deva[काशकृत्स्नम् गुरुलाघवम्]\n- @deva[आपिशलम् दुष्करणम्]\n\n**Terminology:**\n- @deva[अकालक]: lacks @deva[काल]-definitions\n- @deva[गुरुलाघव]: @deva[यत्र उपायानां गौरवं लाघवं च चिन्त्यते] (weighing pros/cons)\n- @deva[दुष्करण]: grammar with @deva[दुषू] as @deva[संज्ञा]; alternatively, @deva[कामशास्त्र]\n\nSee also @ref[2.4.21]."
            }
        },
        "43116": {
            "en": {
                "simple": "An affix comes after a word in the instrumental case to mean 'composed by him,' when the thing composed is a book (@deva[ग्रन्थ]).\n\n**Examples:**\n- @deva[वररुचिना कृताः] → @deva[वाररुचाः श्लोकाः] 'verses composed by Vararuci'\n- @deva[हैकुपादः ग्रन्थः] 'book composed by Haikupāda'\n- @deva[भैकुराटः ग्रन्थः], @deva[जालूकः]\n\nWhy 'a book'? For other things: @deva[तक्षकृतः प्रासादः] 'palace made by Takṣa' (no affix—not a book).\n\nDistinction: @deva[कृत] means 'originated' (an art, a composition); @deva[उपज्ञात] (@ref[4.3.115]) means 'discovered' (existing laws or knowledge found for the first time).",
                "standard": "An affix from @deva[प्राग्दीव्यतोऽण्] (@ref[4.1.83]) comes after a word in @deva[तृतीया] in the @deva[कृत] (composed) sense when a @deva[ग्रन्थ] (book) is meant.\n\n**Examples:** @deva[वाररुचाः श्लोकाः], @deva[हैकुपादः ग्रन्थः], @deva[भैकुराटः ग्रन्थः], @deva[जालूकः]\n\n**@deva[ग्रन्थे] restriction:** @deva[तक्षकृतः प्रासादः] (non-book)—no affix.\n\n**Distinction:** @deva[कृत] = originated (composition, art); @deva[उपज्ञात] = discovered (pre-existing knowledge revealed for the first time).",
                "advanced": "This @deva[सूत्र] teaches the @deva[कृत] (composed) sense for @deva[प्राग्दीव्यतोऽण्] affixes, with @deva[ग्रन्थे] (book) as the referent and @deva[तृतीया] case for the agent.\n\n**Examples:** @deva[वाररुचाः श्लोकाः], @deva[हैकुपादः ग्रन्थः], @deva[भैकुराटः ग्रन्थः], @deva[जालूकः]\n\n**@deva[ग्रन्थे] condition:** Non-books: @deva[तक्षकृतः प्रासादः]—affix doesn't apply.\n\n**@deva[कृत] vs. @deva[उपज्ञात]:** @deva[कृत] = origination (art, composition); @deva[उपज्ञात] = discovery of pre-existing knowledge."
            }
        },
        "43117": {
            "en": {
                "simple": "An affix comes after a word in the instrumental case to mean 'made by him,' when the resulting word is a proper name.\n\n**Examples:** Words for 'honey' (literally 'made by bees'):\n- @deva[मक्षिकाभिः कृतम्] → @deva[माक्षिकम्] 'honey' (made by @deva[मक्षिका], a bee)\n- @deva[कार्मुकम्], @deva[सारघम्], @deva[पौत्तिकम्] (from @deva[सरघा] and @deva[पुत्तिका], other words for 'bee')\n\nDerivation: @deva[मक्षिका] + @deva[अण्] → @deva[माक्षिक] (by @ref[6.4.148]).\n\nThe @deva[ग्रन्थ] (book) condition from the previous rule does not apply here—this is about names for substances.",
                "standard": "An affix from @deva[प्राग्दीव्यतोऽण्] (@ref[4.1.83]) comes after a word in @deva[तृतीया] in the @deva[कृत] sense when the derivative is a @deva[संज्ञा] (proper name).\n\n**Examples (names for honey):**\n- @deva[मक्षिकाभिः कृतम्] → @deva[माक्षिकम्]\n- @deva[कार्मुकम्], @deva[सारघम्], @deva[पौत्तिकम्]\n\n@deva[मक्षिका], @deva[सरघा], @deva[पुत्तिका] = different words for 'bee.'\n\nDerivation: @deva[मक्षिका] + @deva[अण्] → @deva[माक्षिक] by @ref[6.4.148].\n\nThe @deva[ग्रन्थे] restriction of @ref[4.3.116] does not continue.",
                "advanced": "This @deva[सूत्र] teaches @deva[कृत] sense with @deva[संज्ञा] (proper name) as result, distinct from @deva[ग्रन्थ] (@ref[4.3.116]).\n\n**Examples:** @deva[माक्षिकम्], @deva[कार्मुकम्], @deva[सारघम्], @deva[पौत्तिकम्] (all names for honey, 'made by bees').\n\n@deva[मक्षिका], @deva[सरघा], @deva[पुत्तिका] = bee.\n\nDerivation: @deva[मक्षिका] + @deva[अण्] → @deva[माक्षिक] by @ref[6.4.148].\n\nThe @deva[अनुवृत्ति] of @deva[ग्रन्थ] ceases."
            }
        },
        "43118": {
            "en": {
                "simple": "The affix @deva[वुञ्] comes in the @deva[कृत] (made by) sense after words in the @deva[कुलालादि] list, when the resulting word is a proper name.\n\n**Examples:**\n- @deva[कौलालकम्] 'porcelain' (literally 'made by a potter')\n- @deva[वारुडकम्]\n\n**@deva[कुलालादि] list:** @deva[कुलाल] (potter), @deva[वरुड], @deva[चण्डाल], @deva[निषाद], @deva[कर्मार], @deva[सेना], @deva[सिरिध्र], @deva[सैरिन्ध्र], @deva[देवराज], @deva[परिषद्], @deva[वधू], @deva[मधु], @deva[रुरु], @deva[रुद्र], @deva[अनडुह्], @deva[ब्रह्मन्], @deva[कुम्भकार], @deva[श्वपाक], @deva[ध्रुव].",
                "standard": "The affix @deva[वुञ्] comes after @deva[कुलालादि] words in the @deva[कृत] sense when the derivative is a @deva[संज्ञा].\n\n**Examples:** @deva[कौलालकम्] (porcelain, made by a potter), @deva[वारुडकम्]\n\n**@deva[कुलालादि] गण (19):** @deva[कुलाल], @deva[वरुड], @deva[चण्डाल], @deva[निषाद], @deva[कर्मार], @deva[सेना], @deva[सिरिध्र]/​@deva[सिरिन्ध्र], @deva[सैरिन्ध्र]/​@deva[सेन्द्रिय], @deva[देवराज], @deva[परिषद्]/​@deva[पर्षद्], @deva[वधू], @deva[मधु], @deva[रुरु], @deva[रुद्र], @deva[अनडुह्], @deva[ब्रह्मन्], @deva[कुम्भकार], @deva[श्वपाक], @deva[ध्रुव].",
                "advanced": "This @deva[सूत्र] prescribes @deva[वुञ्] after @deva[कुलालादि] words in the @deva[कृत] sense with @deva[संज्ञा] result.\n\n**Examples:** @deva[कौलालकम्], @deva[वारुडकम्]\n\n**@deva[कुलालादि] गण (19):** @deva[कुलाल], @deva[वरुड], @deva[चण्डाल], @deva[निषाद], @deva[कर्मार], @deva[सेना], @deva[सिरिध्र] (@deva[सिरिन्ध्र]), @deva[सैरिन्ध्र] (@deva[सेन्द्रिय]), @deva[देवराज], @deva[परिषद्] (@deva[पर्षद्]), @deva[वधू], @deva[मधु], @deva[रुरु], @deva[रुद्र], @deva[अनडुह्], @deva[ब्रह्मन्], @deva[कुम्भकार], @deva[श्वपाक], @deva[ध्रुव]."
            }
        },
        "43119": {
            "en": {
                "simple": "The affix @deva[अञ्] comes in the @deva[कृत] (made by) sense after the words @deva[क्षुद्रा], @deva[भ्रमर], @deva[वटर], and @deva[पादप], when the resulting word is a proper name. This overrides @deva[अण्].\n\nThe difference between @deva[अण्] and @deva[अञ्] is only in accent.\n\n**Examples (names for honey):**\n- @deva[क्षुद्राभिः कृतम्] → @deva[क्षौद्रम्] 'honey' (made by @deva[क्षुद्रा], small bees)\n- @deva[भ्रामरम्], @deva[वाटरम्], @deva[पादपम्]",
                "standard": "The affix @deva[अञ्] comes after @deva[क्षुद्रा], @deva[भ्रमर], @deva[वटर], and @deva[पादप] in the @deva[कृत] sense with @deva[संज्ञा] result. This debars @deva[अण्].\n\nThe distinction between @deva[अण्] and @deva[अञ्] is accentual.\n\n**Examples:** @deva[क्षौद्रम्] (honey, from small bees), @deva[भ्रामरम्], @deva[वाटरम्], @deva[पादपम्]",
                "advanced": "This @deva[सूत्र] prescribes @deva[अञ्] after @deva[क्षुद्रा], @deva[भ्रमर], @deva[वटर], and @deva[पादप] in the @deva[कृत] sense with @deva[संज्ञा] result, as @deva[अपवाद] to @deva[अण्].\n\nThe @deva[अण्]/​@deva[अञ्] difference is accentual only.\n\n**Examples:** @deva[क्षौद्रम्], @deva[भ्रामरम्], @deva[वाटरम्], @deva[पादपम्]"
            }
        },
        "43120": {
            "en": {
                "simple": "An affix (from the @deva[प्राग्दीव्यतोऽण्] set, @ref[4.1.83]) comes after a word in the genitive (sixth) case to mean 'this belongs to him.'\n\nThe five universal affixes @deva[अण्] etc. (@ref[4.1.83]) and the @deva[घ] etc. affixes (@ref[4.2.93]) apply in this sense.\n\n**Examples:**\n- @deva[उपगोः इदम्] → @deva[औपगवम्] 'belonging to Upagu'\n- @deva[कापटवम्], @deva[राष्ट्रियम्], @deva[अवारपारीणम्]\n\nThe affixes do not apply when the possessed item is @deva[अनन्तर] etc. Thus: @deva[देवदत्तस्य अनन्तरम्] (no affix). The possessed thing should be property, village, kingdom, or dependents.\n\n**Vārtikas:**\n1. The verb @deva[वह्] takes @deva[तृ] and @deva[अण्] with @deva[इट्]: @deva[सवोढुः स्वम्] → @deva[सांवहित्रम्]\n2. @deva[रञ्] comes after @deva[अग्नीध्] meaning 'house'; the base is @deva[भ]-designated: @deva[अग्नीध्रम्] (the @deva[ध] doesn't change to @deva[द] by @ref[8.2.39])\n3. @deva[श्येन्यन्] comes after @deva[समिध्] meaning 'placing': @deva[सामिधेन्यः मन्त्रः] (verses recited while placing fuel on fire), @deva[सामिधेनी ऋक्] (@ref[4.1.41])",
                "standard": "An affix from @deva[प्राग्दीव्यतोऽण्] (@ref[4.1.83]) and @deva[घादि] (@ref[4.2.93]) comes after a word in @deva[षष्ठी] in the sense @deva[तस्येदम्] ('this belongs to him').\n\n**Examples:** @deva[औपगवम्], @deva[कापटवम्], @deva[राष्ट्रियम्], @deva[अवारपारीणम्]\n\n**Restriction:** The possessed item must be property, village, kingdom, or dependents—not @deva[अनन्तर] etc. Thus: @deva[देवदत्तस्य अनन्तरम्] (no affix).\n\n**Vārtikas:**\n1. @deva[वह्] + @deva[तृ] + @deva[इट्] + @deva[अण्] → @deva[सांवहित्रम्] (@deva[सवोढुः स्वम्])\n2. @deva[अग्नीध्] + @deva[रञ्] = @deva[अग्नीध्रम्] (house); @deva[भ]-designation blocks @ref[8.2.39]\n3. @deva[समिध्] + @deva[श्येन्यन्] = @deva[सामिधेनी] (verses for placing fuel); see @ref[4.1.41]",
                "advanced": "This @deva[सूत्र] introduces the @deva[तस्येदम्] (possession) sense for @deva[प्राग्दीव्यतोऽण्] (@ref[4.1.83]) and @deva[घादि] (@ref[4.2.93]) affixes, with @deva[षष्ठी] case.\n\n**Examples:** @deva[औपगवम्], @deva[कापटवम्], @deva[राष्ट्रियम्], @deva[अवारपारीणम्]\n\n**Restriction:** The possessed must be @deva[स्व] (property), @deva[ग्राम], @deva[राष्ट्र], or @deva[जन]—not @deva[अनन्तर] etc.: @deva[देवदत्तस्य अनन्तरम्].\n\n**Vārtikas:**\n1. @deva[वह्] + @deva[तृ]/​@deva[तृण्]/​@deva[तृच्] + @deva[इट्] + @deva[अण्] → @deva[सांवहित्रम्]\n2. @deva[अग्नीध्] + @deva[रञ्] → @deva[अग्नीध्रम्] (house); @deva[भ]-@deva[संज्ञा] blocks @deva[ध] → @deva[द] (@ref[8.2.39])\n3. @deva[समिध्] + @deva[श्येन्यन्] → @deva[सामिधेनी] (fuel-placing mantras); @deva[सामिधेनी ऋक्] by @ref[4.1.41]"
            }
        }
    }

    # Update the data
    for key, value in updates.items():
        data[key] = value

    save_json(commentary_path, data)
    print(f"Updated {len(updates)} sūtras (4.3.106-120)")

if __name__ == "__main__":
    main()
